<?php

/**
 * @file
 * Implements a custom manuscript viewer for the livingstone project.
 */

/**
 * Implements hook_theme().
 */
function livingstone_browse_catalogue_theme() {
  return array(
    'livingstone_browse_catalogue_search' => array(
      'file' => 'includes/browse.catalogue.inc',
      'render element' => 'element',
      'template' => 'theme/livingstone-browse-catalogue-search',
    ),
    'livingstone_browse_catalogue_date_range' => array(
      'file' => 'includes/browse.catalogue.inc',
      'render element' => 'element',
      'template' => 'theme/livingstone-browse-catalogue-date-range',
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function livingstone_browse_catalogue_menu_alter(array &$items) {
  if (isset($items['islandora/search'])) {
    $search_item = &$items['islandora/search'];
    $search_item['page callback'] = 'livingstone_browse_catalogue';
  }
  if (isset($items['islandora/object/%islandora_object'])) {
    $view_object = &$items['islandora/object/%islandora_object'];
    $view_object['page callback'] = 'livingstone_browse_catalogue_object_view_redirect';
    $view_object['page arguments'] = array(2);
  }
}

/**
 * Redirects islandora object to the browse catalogue page.
 *
 * @param AbstractObject $object
 */
function livingstone_browse_catalogue_object_view_redirect(AbstractObject $object) {
  $pid = preg_replace('/:/', '_', $object->id);
  drupal_goto("islandora/search/{$pid}");
}

/**
 * Custom Solr Search Results page for the standard catalogue.
 *
 * @param string|null $query
 *   The search query.
 *
 * @return array
 *   The search form and results.
 */
function livingstone_browse_catalogue($query = NULL) {
  module_load_include('inc', 'livingstone_browse_catalogue', 'includes/browse.catalogue');
  return drupal_get_form('livingstone_browse_catalogue_form', $query);
}
