<?php
/**
 * @file
 * livingstone_partner_nodes_feature.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function livingstone_partner_nodes_feature_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'University of Nebraska',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'partners',
  'language' => 'und',
  'created' => 1490723044,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4d36a3d3-48b0-409e-a0bf-eb1cd66e9197',
  'field_order' => array(
    'und' => array(
      0 => array(
        'value' => 5,
      ),
    ),
  ),
  'field_partner_link' => array(
    'und' => array(
      0 => array(
        'value' => 'http://www.unl.edu',
        'format' => NULL,
      ),
    ),
  ),
  'field_partner_logos' => array(
    'und' => array(
      0 => array(
        'uid' => 1,
        'filename' => 'nebraska.png',
        'uri' => 'public://partners/images/nebraska.png',
        'filemime' => 'image/png',
        'filesize' => 7580,
        'status' => 1,
        'type' => 'image',
        'uuid' => '1d3a3806-1cbf-4a22-8c62-a6a8f7dca656',
        'field_file_image_alt_text' => array(),
        'field_file_image_title_text' => array(),
        'metadata' => array(
          'height' => 51,
          'width' => 127,
        ),
        'alt' => '',
        'title' => '',
        'height' => 51,
        'width' => 127,
        'uuid_features_packaged_file_path' => 'assets/nebraska.png',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:44:04 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'NEH',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'partners',
  'language' => 'und',
  'created' => 1490723044,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '6df94311-37d8-46b4-bd72-03ac1445606c',
  'field_order' => array(
    'und' => array(
      0 => array(
        'value' => 3,
      ),
    ),
  ),
  'field_partner_link' => array(
    'und' => array(
      0 => array(
        'value' => 'http://www.neh.gov/',
        'format' => NULL,
      ),
    ),
  ),
  'field_partner_logos' => array(
    'und' => array(
      0 => array(
        'uid' => 1,
        'filename' => 'neh_logo_horizontal_225.png',
        'uri' => 'public://partners/images/neh_logo_horizontal_225.png',
        'filemime' => 'image/png',
        'filesize' => 11120,
        'status' => 1,
        'type' => 'image',
        'uuid' => 'ad69ba5d-489e-48a8-88d3-ef628752a031',
        'field_file_image_alt_text' => array(),
        'field_file_image_title_text' => array(),
        'metadata' => array(
          'height' => 56,
          'width' => 230,
        ),
        'alt' => 'NEH',
        'title' => 'NEH',
        'height' => 56,
        'width' => 230,
        'uuid_features_packaged_file_path' => 'assets/neh_logo_horizontal_225.png',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:44:04 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Library of Scotland',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'partners',
  'language' => 'und',
  'created' => 1490723044,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9e2f85f7-417c-4eff-b728-5012e055ceef',
  'field_order' => array(
    'und' => array(
      0 => array(
        'value' => 4,
      ),
    ),
  ),
  'field_partner_link' => array(
    'und' => array(
      0 => array(
        'value' => 'http://www.nls.uk',
        'format' => NULL,
      ),
    ),
  ),
  'field_partner_logos' => array(
    'und' => array(
      0 => array(
        'uid' => 1,
        'filename' => 'nls.png',
        'uri' => 'public://partners/images/nls.png',
        'filemime' => 'image/png',
        'filesize' => 8527,
        'status' => 1,
        'type' => 'image',
        'uuid' => '8376ad35-118d-4ebf-86f7-9ba88ffdedc4',
        'field_file_image_alt_text' => array(),
        'field_file_image_title_text' => array(),
        'metadata' => array(
          'height' => 85,
          'width' => 154,
        ),
        'alt' => '',
        'title' => '',
        'height' => 85,
        'width' => 154,
        'uuid_features_packaged_file_path' => 'assets/nls.png',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:44:04 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Trust for Scotland',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'partners',
  'language' => 'und',
  'created' => 1490723044,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b98f27c1-7a2f-4150-9a5f-b960be7deb60',
  'field_order' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_partner_link' => array(
    'und' => array(
      0 => array(
        'value' => 'http://www.nts.org.uk/property/davidlivingstonecentre/',
        'format' => NULL,
      ),
    ),
  ),
  'field_partner_logos' => array(
    'und' => array(
      0 => array(
        'uid' => 1,
        'filename' => 'nts.png',
        'uri' => 'public://partners/images/nts.png',
        'filemime' => 'image/png',
        'filesize' => 8646,
        'status' => 1,
        'type' => 'image',
        'uuid' => '2086c6d2-1552-4751-811b-36ea57f1d35c',
        'field_file_image_alt_text' => array(),
        'field_file_image_title_text' => array(),
        'metadata' => array(
          'height' => 85,
          'width' => 136,
        ),
        'alt' => '',
        'title' => '',
        'height' => 85,
        'width' => 136,
        'uuid_features_packaged_file_path' => 'assets/nts.png',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:44:04 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'UMD Libraries',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'partners',
  'language' => 'und',
  'created' => 1490723044,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e30bfc8e-9d79-4642-812e-f44ba2d7798b',
  'field_order' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_partner_link' => array(
    'und' => array(
      0 => array(
        'value' => 'http://lib.umd.edu/',
        'format' => NULL,
      ),
    ),
  ),
  'field_partner_logos' => array(
    'und' => array(
      0 => array(
        'uid' => 1,
        'filename' => 'umd_libraries.png',
        'uri' => 'public://partners/images/umd_libraries.png',
        'filemime' => 'image/png',
        'filesize' => 12698,
        'status' => 1,
        'type' => 'image',
        'uuid' => '8e591ded-4e16-4a06-8836-c855e39b04b0',
        'field_file_image_alt_text' => array(),
        'field_file_image_title_text' => array(),
        'metadata' => array(
          'height' => 66,
          'width' => 211,
        ),
        'alt' => 'UMD Libraries',
        'title' => 'UMD Libraries',
        'height' => 66,
        'width' => 211,
        'uuid_features_packaged_file_path' => 'assets/umd_libraries.png',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:44:04 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  return $nodes;
}
