<?php

/**
 * @file
 * An viewer for manuscripts with a TEI datastream.
 */

const LIVINGSTONE_SPECTRAL_MANUSCRIPT_CMODEL = "livingstone:spectralManuscriptCModel";
const LIVINGSTONE_SPECTRAL_PAGE_CMODEL = "livingstone:spectralPageCModel";

/**
 * Implements hook_menu().
 */
function livingstone_menu() {
  return array(
    'admin/islandora/livingstone/import/drupal' => array(
      'title' => "Import Manuscript's into Drupal Nodes",
      'description' => "Updates the Drupal content from Fedora, used by search and time line.",
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/node.import.form.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_node_import_form'),
    ),
    'admin/islandora/livingstone/import/fedora' => array(
      'title' => 'Import content from Remote FTP into Local Fedora',
      'description' => 'Updates and adds content from the FTP server into Fedora.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/fedora.import.form.overview.inc',
      'page callback' => 'livingstone_fedora_import_overview_menu_task',
    ),
    'admin/islandora/livingstone/import/fedora/overview' => array(
      'title' => 'Overview',
      'description' => 'Updates and adds content from the FTP server into Fedora.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.overview.inc',
      'page callback' => 'livingstone_fedora_import_overview_menu_task',
      'weight' => -50,
    ),
    'admin/islandora/livingstone/import/fedora/local' => array(
      'title' => 'Local objects',
      'description' => 'Lists all the local objects.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.local.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_local_objects_form'),
      'weight' => -40,
    ),
    'admin/islandora/livingstone/import/fedora/remote' => array(
      'title' => 'Remote objects',
      'description' => 'Lists all the remote objects.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.remote.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_remote_objects_form'),
      'weight' => -30,
    ),
    'admin/islandora/livingstone/import/fedora/add' => array(
      'title' => 'Add',
      'description' => 'Allows the user to add new objects from the FTP.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.add.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_add_objects_form'),
      'weight' => -20,
    ),
    'admin/islandora/livingstone/import/fedora/update' => array(
      'title' => 'Update',
      'description' => 'Allows the user to update existing objects from the FTP.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.update.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_update_objects_form'),
      'weight' => 0,
    ),
    'admin/islandora/livingstone/import/fedora/remove' => array(
      'title' => 'Remove',
      'description' => 'Allows the user to remove stale objects from Fedora.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.remove.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_remove_objects_form'),
      'weight' => 0,
    ),
    'admin/islandora/livingstone/import/fedora/publish' => array(
      'title' => 'Publish / Conceal',
      'description' => 'Allows the user to publish/hide objects in Fedora.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.publish.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_publish_objects_form'),
      'weight' => 10,
    ),
    'admin/islandora/livingstone/import/fedora/errors' => array(
      'title' => 'Error Log',
      'description' => 'Lists any errors that have occurred during import.',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/fedora.import.form.error.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_error_form'),
      'weight' => 20,
    ),
  );
}

/**
 * Implements hook_node_info().
 */
function livingstone_node_info() {
  return array(
    'manuscript' => array(
      'name' => t('Manuscript'),
      'base' => 'node_content',
      'description' => t('Manuscript data synced from Fedora, do not create manually.'),
      'has_title' => TRUE,
      'title_label' => t('Title'),
      'locked' => TRUE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function livingstone_theme() {
  return array(
    'livingstone_form_search_block_search_type' => array(
      'file' => 'theme/theme.inc',
      'render element' => 'element',
    )
  );
}

function livingstone_apachesolr_process_results(&$results) {
  global $user;
  foreach ($results as &$result) {
    if (isset($result['node'])) {
      $node = $result['node'];
      if ($node->bundle == 'manuscript') {
        $node = node_load($node->entity_id);
        if (isset($node->alt_title[LANGUAGE_NONE][0]['value'])) {
          $result['title'] = $node->alt_title[LANGUAGE_NONE][0]['value'];
        }
        $get_value = function ($field, $default) use ($node) {
          return isset($node->{$field}[LANGUAGE_NONE][0]['value']) ?
            $node->{$field}[LANGUAGE_NONE][0]['value'] :
            $default;
        };
        $pid = $get_value('pid');
        $viewable = $get_value('viewable');
        if ($viewable) {
          $result['link'] = url("islandora/search/\"$pid\"", array(
            'absolute' => TRUE,
            'query' => array(
              'view_pid' => $pid,
            ),
          ));
        }
        else {
          $result['link'] = url("islandora/search/\"$pid\"", array('absolute' => TRUE));
        }
      }
    }
  }
}

function livingstone_preprocess_search_result(array &$variables) {
  global $user;
  $result = &$variables['result'];
  if (isset($result['node'])) {
    $node = $result['node'];
    if ($node->type == 'manuscript') {
      $get_value = function ($field, $default) use ($node) {
        return isset($node->{$field}[LANGUAGE_NONE][0]['value']) ?
          $node->{$field}[LANGUAGE_NONE][0]['value'] :
          $default;
      };
      $pid = $get_value('pid');
      $viewable = $get_value('viewable');
      if ($viewable) {
        $variables['url'] = $result['link'] = url("islandora/search/\"$pid\"", array(
          'absolute' => TRUE,
          'query' => array(
            'view_pid' => $pid,
          ),
        ));
      }
      else {
        $variables['url'] = $result['link'] = url("islandora/search/\"$pid\"", array('absolute' => TRUE));
      }
    }
  }
}

/**
 * Implements hook_islandora_derivative_alter().
 * @param array $derivatives
 * @param AbstractObject $object
 */
function livingstone_islandora_derivative_alter(array &$derivatives, AbstractObject $object) {
  foreach ($derivatives as $key => $derivative) {
    if (strpos($derivative['destination_dsid'], 'JP2') === FALSE) {
      unset($derivatives[$key]);
    }
  }
}

/**
 * Implements hook_apachesolr_index_document_build().
 */
function livingstone_apachesolr_index_document_build($document, $entity, $entity_type) {
  if ($entity_type == 'node' && $entity->type == 'manuscript') {
    if (isset($entity->repository_shelfmark['und'][0]['value'])) {
      $document->addField('ts_repository_shelfmark', $entity->repository_shelfmark['und'][0]['value']);
    }
    if (isset($entity->other_versions['und'][0]['value'])) {
      $document->addField('ts_other_versions', $entity->other_versions['und'][0]['value']);
    }
    if (isset($entity->tei['und'][0]['value'])) {
      $document->addField('ts_tei', $entity->tei['und'][0]['value']);
    }
  }
}

/**
 * Implements hook_livingstone_apachesolr_query_alter().
 */
function livingstone_apachesolr_query_alter(DrupalSolrQueryInterface $query) {
  $types = array_keys(array_filter($_GET['type']));
  $web = in_array('web', $types);
  $catalogue = in_array('catalogue', $types);
  $transcriptions = in_array('transcriptions', $types);
  $web_only = $web && !$catalogue && !$transcriptions;
  $manuscript_only = !$web && ($catalogue || $transcriptions);
  $none = !$web && !$catalogue && !$transcriptions;
  if ($none) {
    // Using abort_search causes Apache Solr to error, so we give an impossible
    // query to prevent results.
    // $query->abort_search = TRUE;
    $query->addFilter('bundle', 'section_page');
    $query->addFilter('bundle', 'manuscript');
  }
  if ($web_only) {
    $query->addFilter('bundle', 'section_page');
  }
  if ($manuscript_only) {
    $query->addFilter('bundle', 'manuscript');
  }
  // Reset query filter.
  if (!$web) {
    $query->replaceParam('qf', '');
  }
  if ($catalogue) {
    $query->addParam('qf', array(
      'label^1.0',
      'sm_project_id^1.0',
      'sm_pid^1.0',
      'sm_dates',
      'sm_creators^0.5',
      'sm_addressees^0.5',
      'sm_places_created',
      'sm_extent_pages',
      'sm_extent_size',
      'sm_genres',
      'sm_copy_of_item',
      'sm_catalogue_number',
      'ts_repository_shelfmark',
      'ts_other_versions',
      'dm_date_range_start',
      'dm_date_range_end',
    ));
  }
  if ($transcriptions) {
    $query->addParam('qf', array('ts_tei^1.0'));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function livingstone_form_search_block_form_alter(array &$form, array &$form_state) {
  $module_path = drupal_get_path('module', 'livingstone');
  $form['#attached'] = array(
    'js' => array(
      "$module_path/js/search-form.js",
    ),
  );
  $form['search_type'] = array(
    '#prefix' => '<span class="search-type" style="display:none">',
    '#suffix' => '</span>',
    '#theme' => 'livingstone_form_search_block_search_type',
    '#type' => 'checkboxes',
    '#default_value' => drupal_map_assoc(array('web', 'catalogue', 'transcriptions')),
    '#options' => array(
      'web' => t('Search web pages'),
      'catalogue' => t('Search digital catalogue'),
      'transcriptions' => t('Search transcriptions'),
    ),
  );
  $form['#submit'][] = 'livingstone_search_block_submit';
}

/**
 * Sets the type argument for the search query.
 */
function livingstone_search_block_submit(array $form, array &$form_state) {
  if ($form_state['values']['search_type']) {
    $form_state['redirect'] =  array(
      $form_state['redirect'],
      array(
        'query' => array(
          'type' => $form_state['values']['search_type'],
        ),
      ),
    );
  }
}

/**
 * Implements hook_islandora_required_objects().
 */
function livingstone_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'livingstone');
  // Spectral manuscript content model.
  $spectral_manuscript_cmodel = $connection->repository->constructObject(LIVINGSTONE_SPECTRAL_MANUSCRIPT_CMODEL);
  $spectral_manuscript_cmodel->owner = 'fedoraAdmin';
  $spectral_manuscript_cmodel->label = 'Spectral Manuscript Content Model';
  $spectral_manuscript_cmodel->models = 'fedora-system:ContentModel-3.0';
  $ds_composite = $spectral_manuscript_cmodel->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $ds_composite->label = 'DS-COMPOSITE-MODEL';
  $ds_composite->mimetype = 'application/xml';
  $ds_composite->setContentFromFile("$module_path/xml/livingstone_spectralManuscriptCModel_ds_composite_model.xml", FALSE);
  $spectral_manuscript_cmodel->ingestDatastream($ds_composite);
  // Spectral page content model.
  $spectral_page_cmodel = $connection->repository->constructObject(LIVINGSTONE_SPECTRAL_PAGE_CMODEL);
  $spectral_page_cmodel->owner = 'fedoraAdmin';
  $spectral_page_cmodel->label = 'Spectral Page Content Model';
  $spectral_page_cmodel->models = 'fedora-system:ContentModel-3.0';
  $ds_composite = $spectral_page_cmodel->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $ds_composite->label = 'DS-COMPOSITE-MODEL';
  $ds_composite->mimetype = 'application/xml';
  $ds_composite->setContentFromFile("$module_path/xml/livingstone_spectralPageCModel_ds_composite_model.xml", FALSE);
  $spectral_page_cmodel->ingestDatastream($ds_composite);
  return array(
    'livingstone' => array(
      'title' => t('Livingstone'),
      'objects' => array(
        $spectral_manuscript_cmodel,
        $spectral_page_cmodel,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_derivative().
 */
function livingstone_livingstone_spectralManuscriptPageCModel_islandora_derivative() {
  module_load_include('inc', 'livingstone', 'includes/fedora.import');
  $large_image_module_path = drupal_get_path('module', 'islandora_large_image');
  $dsids = db_select(LIVINGSTONE_FEDORA_IMPORT_REMOTE_DATASTREAM_TABLE, 'r')
    ->distinct()
    ->fields('r', array('DSID'))
    ->condition('r.DSID', '%OBJ', 'LIKE')
    ->execute()
    ->fetchCol(0);
  foreach ($dsids as $dsid) {
    $format = preg_replace('/_OBJ$/', '', $dsid);
    $format = strtoupper($format);
    $derivatives[] = array(
      'source_dsid' => "{$format}_OBJ",
      'destination_dsid' => "${format}_JP2",
      'function' => array('livingstone_spectral_create_jp2_derivative'),
    );
  }
  return $derivatives;
}

function livingstone_spectral_get_uploaded_file(AbstractObject $object, $src_dsid) {
  $base_name = str_replace(':', '-', $object->id);
  $mime_detector = new MimeDetect();
  $ext = $mime_detector->getExtension($object[$src_dsid]->mimeType);
  $filename = file_create_filename("{$base_name}_{$src_dsid}.{$ext}", 'temporary://');
  $object[$src_dsid]->getContent($filename);
  return $filename;
}

/**
 *
 */
function livingstone_spectral_create_jp2_derivative(AbstractObject $object, $force, array $derivative) {
  module_load_include('inc', 'islandora_large_image', 'includes/derivatives');
  module_load_include('inc', 'islandora_large_image', 'includes/utilities');
  $base_name = str_replace(':', '-', $object->id);
  $src_dsid = $derivative['source_dsid'];
  $dest_dsid = $derivative['destination_dsid'];
  if ($force || !isset($object[$dest_dsid])) {
    $to_return = array(
      'success' => FALSE,
      'messages' => array(),
    );
    $uploaded_file = livingstone_spectral_get_uploaded_file($object, $src_dsid);
    $lossless = variable_get('islandora_lossless', FALSE);
    if (islandora_large_image_is_jp2($uploaded_file) && !$lossless) {
      $derivative_file = $uploaded_file;
    }
    else {

      $depth = islandora_large_image_get_bit_depth($uploaded_file);

      // Create JP2 with kakadu.
      $kakadu = variable_get('islandora_use_kakadu', !islandora_large_image_check_imagemagick_for_jpeg2000());
      $mime = strtolower($object[$src_dsid]->mimetype);
      if ($mime == 'image/jpeg' || $mime == 'image/jpg' || $depth < 8) {
        $kakadu = FALSE;
      }
      // Use lossless if the image would look too bad with compression.
      if (!$lossless) {
        $identify = islandora_large_image_get_identify();
        // Define all these variables in one call for a large performance gain.
        $file_path = drupal_realpath($uploaded_file);
        list($height, $width, $y_resolution, $x_resolution) = explode(
          ',',
          exec(escapeshellcmd("$identify -format \"%h,%W,%y,%x\" $file_path"))
        );
        if (((int) $x_resolution < 300 || (int) $y_resolution < 300) ||
          ($height < 1024 || $width < 1024)) {
          $lossless = TRUE;
        }
      }

      if ($kakadu) {
        // Create JP2.
        if (!$lossless) {
          $derivative_file = islandora_large_image_kdu_compress($uploaded_file, "temporary://{$base_name}_JP2.jp2");
        }
        else {
          $derivative_file = islandora_large_image_kdu_compress(
            $uploaded_file,
            "temporary://{$base_name}_JP2.jp2",
            'Creversible=yes -rate -,1,0.5,0.25 Clevels=5'
          );
        }
        if ($derivative_file === FALSE) {
          $to_return['messages'][] = array(
            'message' => t("Kakadu failed. Trying ImageMagick ..."),
            'type' => 'dsm',
            'severity' => 'status',
          );
          // Force retry with ImageMagick if Kakadu has failed.
          $kakadu = FALSE;
        }
      }
      if (!$kakadu) {
        $args = islandora_large_image_get_args($lossless);
        if ($depth < 8) {
          $args = array_merge($args, array("-depth 8"));
        }
        $derivative_file = islandora_large_image_imagemagick_convert(
          $uploaded_file,
          "temporary://{$base_name}_JP2.jp2",
          $args);
      }
    }
    if ($derivative_file === FALSE) {
      $to_return['messages'][] = array(
        'message' => t('Failed to create JP2 derivative.'),
        'type' => 'watchdog',
        'severity' => WATCHDOG_ERROR,
      );
    }
    else {
      $added_successfully = islandora_large_image_add_datastream($object, $dest_dsid, $derivative_file, 'image/jp2', t('JPEG 2000'));
      if (TRUE === $added_successfully) {
        $to_return['messages'][] = array(
          'message' => t('Created JP2 derivative.'),
          'type' => 'dsm',
          'severity' => 'status',
        );
        $to_return['success'] = TRUE;
      }
      else {
        $to_return['messages'][] = array(
          'message' => t('Failed to add JP2 derivative to the object. Error message: @message', array('@message' => $added_successfully)),
          'type' => 'dsm',
          'severity' => 'warning',
        );
      }
    }
    file_unmanaged_delete($uploaded_file);
    file_unmanaged_delete($derivative_file);
    return $to_return;
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function livingstone_field_formatter_info() {
  return array(
    'transcript_formatter' => array(
      'label' => t('Transcript Display'),
      'field types' => array('double_field'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function livingstone_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  module_load_include('inc', 'livingstone', 'includes/utilities');
  $transcriptions = array(
    '#prefix' => '<div id="transcripts">',
    '#suffix' => '</div>',
  );
  $documents = array();
  foreach ($items as $item) {
    $value = preg_replace('/liv_/', 'liv:', $item['first']);
    $documents[$value] = $item['second'];
  }
  $module_path = drupal_get_path('module', 'livingstone');
  drupal_add_css("$module_path/css/transcription-viewer.css");
  drupal_add_js("$module_path/modules/viewer/js/livingstone-manuscript-viewer-transcript-tooltips.js");
  drupal_add_js("$module_path/modules/viewer/lib/qtip2/3.0.3/jquery.qtip.min.js");
  drupal_add_css("$module_path/modules/viewer/lib/qtip2/3.0.3/jquery.qtip.min.css");
  drupal_add_js("$module_path/js/livingstone-transcriptions.js");
  list($document) = each($documents);
  list($second_document) = each($documents);
  reset($documents);
  $transcription_url = url("livingstone/manuscript/{$document}/transcript");
  $second_transcription_url = isset($second_document) ?
    url("livingstone/manuscript/{$second_document}/transcript") :
    $transcription_url;
  return array(
    array(
      'viewer' => array(
        '#prefix' => '<div id="transcription-viewer">',
        '#suffix' => '</div>',
        'panels' => array(
          array(
            '#prefix' => '<div class="pane">',
            '#suffix' => '</div>',
            'toolbar' => array(
              '#prefix' => '<div class="transcription-viewer-toolbar">',
              '#suffix' => '</div>',
              'transcription' => array(
                '#type' => 'select',
                '#attributes' => array(
                  'class' => array('transcript')
                ),
                '#options' => $documents,
                '#value' => $document,
              ),
              'date' => array(
                '#type' => 'select',
                '#attributes' => array(
                  'class' => array('date')
                ),
                '#options' => array('Select date'),
              ),
            ),
            'content' => array(
              '#prefix' => '<div class="transcription-viewer-content">',
              '#markup' => "<iframe src=\"{$transcription_url}\"></iframe>",
              '#suffix' => '</div>',
            ),
          ),
          array(
            '#prefix' => '<div class="pane">',
            '#suffix' => '</div>',
            'toolbar' => array(
              '#prefix' => '<div class="transcription-viewer-toolbar">',
              '#suffix' => '</div>',
              'transcription' => array(
                '#type' => 'select',
                '#attributes' => array(
                  'class' => array('transcript')
                ),
                '#options' => $documents,
                '#value' => isset($second_document) ? $second_document : $document,
              ),
              'date' => array(
                '#type' => 'select',
                '#attributes' => array(
                  'class' => array('date')
                ),
                '#options' => array('Select date'),
              ),
            ),
            'content' => array(
              '#prefix' => '<div class="transcription-viewer-content">',
              '#markup' => "<iframe src=\"{$second_transcription_url}\"></iframe>",
              '#suffix' => '</div>',
            ),
          ),
        ),
      ),
    ),
  );
}
