<?php
/**
 * @file
 * livingstone_nodequeue_items_feature.features.uuid_nodequeue_item.inc
 */

/**
 * Implements hook_uuid_features_default_nodequeue_items().
 */
function livingstone_nodequeue_items_feature_uuid_features_default_nodequeue_items() {
  $nodequeue_items = array();

  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => '2fad8685-ae1e-42f2-815a-4d94a94025a7',
    'position' => 6,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => '439d7063-9706-41a2-adef-e997db6b2311',
    'position' => 2,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => '78d62fa4-716c-41ee-94ef-b09eb07b8903',
    'position' => 8,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => '7f02dba0-1cfc-468b-acf2-2092bda28149',
    'position' => 10,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => '85a0a40c-9dfc-4167-aff4-0797f78db4c0',
    'position' => 7,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => '9e853e69-ef25-40c6-bd0a-e296e3849c47',
    'position' => 12,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => 'b49b7671-f0d6-47e9-8826-f97b878a6831',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => 'cc3ab471-98ad-431e-a7b7-8e0be4959241',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => 'd3443f49-2d3b-45ee-b815-d0a762ab0d8e',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => 'd7005121-41b1-4918-95a8-2e759f91461b',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => 'da31bc5d-a889-49c7-8a85-2c9fc373af4d',
    'position' => 11,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'about_this_site',
    'node_uuid' => 'fbe43c27-596e-4517-9823-2bfd3ff3cb55',
    'position' => 9,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '10e996f3-d9b0-4602-b09b-5b943343b79f',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '221eacac-416a-4414-9ce9-707c337043df',
    'position' => 7,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '2fafd228-a8e3-4e3c-99af-4e1ddf77b09b',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '57af40fe-d6fd-419f-a7a4-633af9bc77ec',
    'position' => 8,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '77d30e4e-f5dd-4ec0-a619-a8eb85d9b4f4',
    'position' => 6,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '906a2148-9b4b-4981-b5e7-82412ba8b4c2',
    'position' => 9,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '9422bd16-b593-482e-8821-21b3ed99a80d',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => '970d3a26-234b-4a39-aa82-d8931b11e919',
    'position' => 2,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'behind_the_scenes',
    'node_uuid' => 'b1d5286c-4650-4d31-bafe-d33892f53573',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => '30c2c5e6-789e-4e36-8de8-e9d0102b55eb',
    'position' => 6,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => '58e469f4-872f-42ba-85b6-1058ac1f5538',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => '6359d32f-8c12-4096-a78f-8cff0fc04ec8',
    'position' => 2,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => '91f40778-9b1b-495e-80ff-c10fe1d903c8',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => 'a196eb07-12c3-4133-b6e8-5a46fc2d9256',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => 'c301ad6d-8a42-4467-854c-5ba54a7f63ad',
    'position' => 7,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => 'ef7677b7-0212-4c34-bb8e-ce826eefb0af',
    'position' => 8,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'in_his_own_words',
    'node_uuid' => 'f08e9f08-303d-448e-8c8a-d09c5dfba96e',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => '0bda8609-f62b-4428-9446-3a3307b7ea15',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => '2dc0d511-087c-40dc-ab6b-4fe769dd03f7',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => '76ab1aa0-2bf4-4c42-adf7-c8c4ee960236',
    'position' => 2,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => '77590f20-a6f3-4721-85ff-22b52973f313',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => 'a7a76aaf-60bb-456e-a0c3-150596f6c7b7',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => 'c25a3705-73b9-4094-bc06-aa5f39d93935',
    'position' => 8,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => 'c97b074f-908e-4022-8ce9-e23418a99796',
    'position' => 6,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => 'ce8c001e-9bd3-4995-8b37-37477601e8f8',
    'position' => 7,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'life_times',
    'node_uuid' => 'd90534e6-fa44-4235-af76-80c34119b996',
    'position' => 9,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => '58a3243f-182c-4d5a-b174-293eaaf2129b',
    'position' => 9,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => '686d8c7f-1386-4692-b780-cfc9081e3872',
    'position' => 6,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => '749fac17-d2c6-49e7-bfed-0aca417379b5',
    'position' => 7,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => '75c25c6c-c491-4059-b446-3562d7518c95',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => '7fbeae31-b1a8-46f0-9529-67f90d0e36f5',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => '8082ba50-e1cb-47bb-b5b8-18c9d2aeb395',
    'position' => 2,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => '8229df32-720a-4447-82e1-9f17f8de0d71',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => 'b33a7f9f-edeb-4611-a294-8d92020bf9f0',
    'position' => 8,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'our_technology',
    'node_uuid' => 'f2928a2c-8998-407f-beab-43aaa7679c45',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'partners',
    'node_uuid' => '4d36a3d3-48b0-409e-a0bf-eb1cd66e9197',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'partners',
    'node_uuid' => '6df94311-37d8-46b4-bd72-03ac1445606c',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'partners',
    'node_uuid' => '9e2f85f7-417c-4eff-b728-5012e055ceef',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'partners',
    'node_uuid' => 'b98f27c1-7a2f-4150-9a5f-b960be7deb60',
    'position' => 2,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'partners',
    'node_uuid' => 'e30bfc8e-9d79-4642-812e-f44ba2d7798b',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'resouces',
    'node_uuid' => '08cc1752-d8e8-4f69-a2f5-b9b89d734f88',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'resouces',
    'node_uuid' => '255bf215-fc27-4341-8695-a0a7b4a38d6f',
    'position' => 6,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'resouces',
    'node_uuid' => '88827c23-c292-4e86-ad55-2431062e5986',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'resouces',
    'node_uuid' => '97fc9cb2-fc88-4a58-86b4-4cfaf7d4cf6e',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'resouces',
    'node_uuid' => 'd6801fb9-85ff-4b39-bc07-6378bc6421db',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'resouces',
    'node_uuid' => 'e5b11e17-a894-4e30-b7fa-fabfc2177fdc',
    'position' => 2,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'slides',
    'node_uuid' => '172a1459-8c87-48ef-9720-b448bdec0cdb',
    'position' => 7,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'slides',
    'node_uuid' => '1f7f6ad8-9f18-469d-8f1f-61d041a457fd',
    'position' => 1,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'slides',
    'node_uuid' => '24eebd91-fc24-4900-b186-5e45650602f4',
    'position' => 4,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'slides',
    'node_uuid' => '51a98968-99a5-4951-bd65-5adbbae53fe6',
    'position' => 5,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'slides',
    'node_uuid' => '6854e5a4-251b-4647-95c6-7337d2664693',
    'position' => 3,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'slides',
    'node_uuid' => 'bb29c92f-d532-434e-8a8c-ea16b5117da5',
    'position' => 6,
  );
  $nodequeue_items[] = array(
    'queue_name' => 'slides',
    'node_uuid' => 'd9adf31f-f3e8-4660-bc08-cb9bf6eeb2ea',
    'position' => 2,
  );
  return $nodequeue_items;
}
