<?php
/**
 * @file
 * livingstone_repository_info_nodes_feature.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function livingstone_repository_info_nodes_feature_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'National Archives and Records Service of South Africa',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '010f335e-4053-4d7f-b548-f391b22a6598',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Cape Town',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no2005118051',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"National Archives and Records Service of South Africa"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'National Archives and Records Service of South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Smithsonian Institution. Libraries. Joseph F. Cullman 3rd Library of Natural History',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '025cb011-6e69-4f96-92eb-4906e421aebf',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Washington, D.C.',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Smithsonian Institution. Libraries. Joseph F. Cullman 3rd Library of Natural History"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Smithsonian Institution. Libraries. Joseph F. Cullman 3rd Library of Natural History',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of California, Berkeley. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0bb048b0-d537-47bf-a590-e8913de7bc68',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Berkeley',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n83186537',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of California, Berkeley. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of California, Berkeley. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'California',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Dove Cottage and the Wordsworth Museum',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0c19ee5a-517f-4942-b605-31c2e69c45c0',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Grasmere',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n92018924',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Dove Cottage and the Wordsworth Museum"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Dove Cottage and the Wordsworth Museum',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Museum of the Royal Navy (Great Britain)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0d474cbb-2b75-45d4-a299-89a6c96d033b',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Portsmouth',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/nb2011009634',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"National Museum of the Royal Navy (Great Britain)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'National Museum of the Royal Navy (Great Britain)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Chas. J. Sawyer, Ltd.',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0e7b0e73-e8f7-49b5-8286-986d3a9fcb83',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/nr98012036',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Chas. J. Sawyer, Ltd."',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Chas. J. Sawyer, Ltd.',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Cory Library for Historical Research',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '122d077d-e7b5-4e44-beaa-86a1f00b5c7a',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Grahamstown',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n83239596',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Cory Library for Historical Research"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Cory Library for Historical Research',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'EMMS International',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '147adb77-e2a5-43bd-bc6e-f9cf543845cb',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Edinburgh',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/nb2005015090',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"EMMS International"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'EMMS International',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Library of Wales. Department of Manuscripts and Records',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '1b156c2f-1c14-4e05-a8d3-8d10735149e8',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Aberystwyth',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Wales',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/nr96036170',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"National Library of Wales. Department of Manuscripts and Records"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'National Library of Wales. Department of Manuscripts and Records',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of London. School of Oriental and African Studies',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '1b6bb9c8-f6cc-4da2-89af-0d1a6a4f78bb',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n79092591',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of London. School of Oriental and African Studies"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of London. School of Oriental and African Studies',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'British Library. India Office Records and Private Papers',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '1be3f32a-c6ba-47f2-8a62-95da652050a9',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50059129 ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"British Library. India Office Records and Private Papers"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'British Library. India Office Records and Private Papers',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of Strathclyde. Andersonian Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '24972970-43d2-41eb-9b2f-a0db3289e518',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Glasgow',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no99000897',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of Strathclyde. Andersonian Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of Strathclyde. Andersonian Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Fitzwilliam Museum',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '28c62658-abc7-4f66-9524-b22518a8d237',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Cambridge',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n81041657',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Fitzwilliam Museum"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Fitzwilliam Museum',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal College of Physicians and Surgeons of Glasgow',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2a1bbf45-b40d-4e50-8da0-9d1d6f8d9fe4',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Glasgow',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50069411',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal College of Physicians and Surgeons of Glasgow"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal College of Physicians and Surgeons of Glasgow',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Brenthurst Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '356018f2-fa48-49b3-8f8b-5dcf8e77d5a6',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Johannesburg',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n85315461',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Brenthurst Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Brenthurst Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Livingstone Museum',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '369c4330-8ce2-4d8b-baa6-fa696e034da4',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Livingstone',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Zambia',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n84192693 ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Livingstone Museum"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Livingstone Museum',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Kelvingrove Art Gallery and Museum',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '373de581-ea0b-4d22-9545-547ac5728762',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Glasgow',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n2010019893',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Kelvingrove Art Gallery and Museum"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Kelvingrove Art Gallery and Museum',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Imperial College, London. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '391b0244-894b-4c0d-9645-40bb7e911d8f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/nr2004014787',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Imperial College, London. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Imperial College, London. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Church of All Saints (Helmsley, England)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3ab63890-353f-45d2-9c6a-41dc748b502a',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Helmsley',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Church of All Saints (Helmsley, England)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Church of All Saints (Helmsley, England)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Wellcome Institute for the History of Medicine. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3b38f175-0d67-440a-abdf-3acf011d1937',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n84067847',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Wellcome Institute for the History of Medicine. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Wellcome Institute for the History of Medicine. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Service Protestant de Missions et de Relations Internationale',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4191a58a-eb86-4de0-be45-417866604586',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Paris',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'France',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Service Protestant de Missions et de Relations Internationale"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Service Protestant de Missions et de Relations Internationale',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Lincoln Cathedral. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4378a79b-e956-4499-8b89-cb0c03752c8c',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Lincoln',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50056838',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Lincoln Cathedral. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Lincoln Cathedral. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'St. John\'s University (Collegeville, Minnesota). Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '44274ead-bbf2-4dfb-a56a-5260fe0a713a',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Collegeville',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50046537',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"St. John\'s University (Collegeville, Minnesota). Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'St. John\'s University (Collegeville, Minnesota). Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Minnesota',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Durban Municipal Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '47539bf1-3f86-4f87-b619-51202c54e335',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Durban',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n82047796',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Durban Municipal Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Durban Municipal Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal Geographical Society (Great Britain)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4768e8c1-8039-4dde-a229-5c87e8935921',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80152915',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal Geographical Society (Great Britain)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal Geographical Society (Great Britain)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Graaff-Reinet Museum',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '47d337b2-3d5d-43ac-84ef-79662cd16223',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Graaf-Reinet',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no2009004588',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Graaff-Reinet Museum"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Graaff-Reinet Museum',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Auckland Libraries',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '47e1b9f5-2079-47b8-b141-618c4fbef072',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Auckland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'New Zealand',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no2012008390',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Auckland Libraries"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Auckland Libraries',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Bodleian Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4c245692-ae7c-4526-9a72-8b5a15f1f7ad',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Oxford',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80020306',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Bodleian Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Bodleian Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University College of Wales (Aberystwyth, Wales). Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '502b7338-68e3-4746-a3d7-d90a6fc9c052',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Aberystwyth',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Wales',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n77018046',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University College of Wales (Aberystwyth, Wales). Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University College of Wales (Aberystwyth, Wales). Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Church Missionary Society',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '50abaa35-dac9-433a-b00a-0e7c4d87af74',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no99081782 ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Church Missionary Society"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Church Missionary Society',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of Wisconsin-Milwaukee Libraries. American Geographical Society Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '542eba37-4967-4cfe-b55f-92f83324df6d',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Milwaukee',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of Wisconsin-Milwaukee Libraries. American Geographical Society Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of Wisconsin-Milwaukee Libraries. American Geographical Society Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Wisconsin',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Archives (Great Britain)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '57e7072e-d3ab-4164-a062-420e3dc5a367',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/nr2003012888',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"National Archives (Great Britain)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'National Archives (Great Britain)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal Society of Arts (Great Britain). Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '5ae3c865-83a8-48b0-b0c5-28410295eefd',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal Society of Arts (Great Britain). Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal Society of Arts (Great Britain). Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of Minnesota. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '63de1445-98cf-48bd-ac37-459d7c172ef6',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Minneapolis',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n86086029',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of Minnesota. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of Minnesota. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Minnesota',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Institut de France. Bibliothèque',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '64b18a42-7f10-4d5d-9403-90766a1bbe5f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Paris',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'France',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80084526',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Institut de France. Bibliothèque"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Institut de France. Bibliothèque',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Memorial University of Newfoundland. Centre for Newfoundland Studies',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '650d1e1c-e51e-4696-baef-2467efdebc00',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Newfoundland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Canada',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n93070954',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Memorial University of Newfoundland. Centre for Newfoundland Studies"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Memorial University of Newfoundland. Centre for Newfoundland Studies',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'H.F. Wilson Collection (St. Fillans, Scotland)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '671de421-b2a2-4e4f-9e63-0405281baa5a',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'St. Fillans',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"H.F. Wilson Collection (St. Fillans, Scotland)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'H.F. Wilson Collection (St. Fillans, Scotland)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal Greenwich Observatory. Archives',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '69127771-9c98-4125-bb06-120f9e8038f9',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Sussex',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal Greenwich Observatory. Archives"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal Greenwich Observatory. Archives',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'David Livingstone Centre',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '6a4438ba-4589-4560-8087-1ca836b84ac7',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Blantyre',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no2009190108',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"David Livingstone Centre"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'David Livingstone Centre',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of Glasgow. Archives   ',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '71c89e40-9dd1-42a2-8458-f26e24bc3e77',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Glasgow',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n78027597   ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/islandora/search?f%5B%5D=repository_ms%3A%22University+of+Glasgow.+Archives%22',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of Glasgow. Archives   ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Dunedin Public Library (Dunedin, N.Z.)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7abaaf6f-6ee9-4c88-996a-5ec1b5fe30f8',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Dunedin',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'New Zealand',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no2004083625',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Dunedin Public Library (Dunedin, N.Z.)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Dunedin Public Library (Dunedin, N.Z.)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal Commonwealth Society. Library  ',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7edca31e-495f-40b5-81b3-7749b1b6712c',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n81147436 ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal Commonwealth Society. Library  "',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal Commonwealth Society. Library  ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal College of Surgeons of England  ',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7f0643bc-36ef-4c57-820a-6fb70a25bdba',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50043077',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal College of Surgeons of England  "',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal College of Surgeons of England  ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of Cape Town Libraries. Special Collections ',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8054ff3e-4aad-457f-a5bc-8802f34ba84f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Rondebosch',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/islandora/search?f%5B%5D=repository_ms%3A%22University+of+Cape+Town+Libraries.+Special+Collections%22',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of Cape Town Libraries. Special Collections ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Private owner',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '80dafbfc-1de4-43f9-81aa-90a848d448eb',
  'field_repo_city' => array(),
  'field_repo_country' => array(),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Private owner"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Private owner',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Pietermaritzburg Archives Repository',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '82c52064-3c31-452a-a7ac-a60640d8f018',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Pietermaritzburg',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n98101118',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Pietermaritzburg Archives Repository"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Pietermaritzburg Archives Repository',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Munger Africana Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '865b1838-454f-4552-9913-155656e6f532',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Pasadena',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50063332',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Munger Africana Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Munger Africana Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'California',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of Fort Hare. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '86d916e9-35a4-4125-b375-99652f2df017',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Fort Hare',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n82090166',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of Fort Hare. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of Fort Hare. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'New College (University of Edinburgh).‏ Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '897e9d66-93bd-4fdb-8338-69cd46caf418',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Edinburgh',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/nb2010032725',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/islandora/search?f%5B%5D=repository_ms%3A%22New+College+%28University+of+Edinburgh%29.+Library%22',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'New College (University of Edinburgh).‏ Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Harold Strange Library of African Studies',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8cd45e0d-fb08-4ef2-b6e0-f06fa41d37e4',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Johannesburg',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n96034554',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Harold Strange Library of African Studies"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Harold Strange Library of African Studies',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Library of Scotland',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8d35ffad-fc5b-4069-93c5-8196114c7f69',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Edinburgh',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80044899',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"National Library of Scotland"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'National Library of Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Durban Museum and Art Gallery',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8e851116-198d-42ad-82c7-d2eccb0e4e8a',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Durban',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n87913613',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Durban Museum and Art Gallery"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Durban Museum and Art Gallery',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal Botanic Gardens, Kew. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8f73a718-0ee8-4ca9-8f94-3eb2c6ec4559',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Surrey',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80093565',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal Botanic Gardens, Kew. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal Botanic Gardens, Kew. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Mitchell Library (Glasgow, Scotland)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '925e482a-0f2d-45b6-84ed-d711cfae6fa1',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Glasgow',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n85058116',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Mitchell Library (Glasgow, Scotland)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Mitchell Library (Glasgow, Scotland)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Parish Church (Helmsley, Yorkshire, England)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '92c44576-a599-41f9-ad2c-efe284f20884',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Yorkshire',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Parish Church (Helmsley, Yorkshire, England)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Parish Church (Helmsley, Yorkshire, England)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'South Africa. Parliament. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '945f3e89-6b7d-4a0d-821a-a5283a3a9075',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Cape Town',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"South Africa. Parliament. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa. Parliament. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Musée royal de l\'Afrique centrale',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9b7858ac-8785-4ae9-93b4-eb7d8736e5f9',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Tervuren',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Belgium',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80126084',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Musée royal de l\'Afrique centrale"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Musée royal de l\'Afrique centrale',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of the Witwatersrand. William Cullen Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a10d6108-9037-4c41-89af-cf1ebd8c9eaf',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Johannesburg',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n2001047309',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of the Witwatersrand. William Cullen Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of the Witwatersrand. William Cullen Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Peace Memorial Museum (Zanzibar)',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a1dedda8-524e-4826-93bc-4cad052f6dcd',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Zanzibar',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Tanzania',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no2014164503.html',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Peace Memorial Museum (Zanzibar)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Peace Memorial Museum (Zanzibar)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Columbia University Libraries. Burke Library at Union Theological Seminary',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a772520d-c838-4e5e-9b98-85d958b97630',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'New York',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Columbia University Libraries. Burke Library at Union Theological Seminary"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Columbia University Libraries. Burke Library at Union Theological Seminary',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'New York',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Indiana University of Pennsylvania. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a8c7565b-f579-43bf-83ac-60789e551a10',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Indiana',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Indiana University of Pennsylvania. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Indiana University of Pennsylvania. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Pennsylvania',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Inveraray Castle (Argyllshire, Scotland). Argyll Monuments',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a90159e1-2f6e-4ae6-9eba-0a050fcd019f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Argyllshire',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Inveraray Castle (Argyllshire, Scotland). Argyll Monuments"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Inveraray Castle (Argyllshire, Scotland). Argyll Monuments',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Foskett Collection',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'acdc4716-e05d-4a82-818c-f78b7c3fd5f0',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Ambleside',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Foskett Collection"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Foskett Collection',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'E.M. Private owner',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ae5dfe9d-7cc2-4af7-a19a-7581cd715bd8',
  'field_repo_city' => array(),
  'field_repo_country' => array(),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"E.M. Private owner"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'E.M. Private owner',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of East Anglia',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'aec8a665-0eb2-4b66-9514-10a816b1e196',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'East Anglia',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80097575',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University of East Anglia"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of East Anglia',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Peabody Essex Museum',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b04eec2f-8590-40e1-b523-0000a328625f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Salem',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no94033211 ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Peabody Essex Museum"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Peabody Essex Museum',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Massachusetts',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Museums of Scotland',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b3c22e0b-70e4-4aba-bc05-863275efb577',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Edinburgh',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n89641273',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"National Museums of Scotland"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'National Museums of Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Michigan State University. Libraries. Special Collections Division',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'en',
  'created' => 1502302737,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b7417e00-f7c0-4de0-9f32-5e7d3622b4ec',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'East Lansing',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n93024330.html',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/islandora/search/?f[0]=repository_ms:"Michigan State University. Libraries. Special Collections Division"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Michigan State University. Libraries. Special Collections Division',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Michigan',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 1,
  ),
  'url_alias' => array(),
  'date' => '2017-08-09 18:18:57 +0000',
  'user_uuid' => '22a82bbc-8b0b-4c39-99e4-a242ac324e01',
);
  $nodes[] = array(
  'title' => 'Yale University. Divinity School. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b766285b-2101-4a15-b8db-fef0e54050a8',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'New Haven',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n88657374',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Yale University. Divinity School. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Yale University. Divinity School. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Connecticut',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Billy Graham Center. Archives',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b83055c2-dbc8-47e7-a3ca-69c0f16377b4',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Wheaton',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n90619008',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Billy Graham Center. Archives"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Billy Graham Center. Archives',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Illinois',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Zimbabwe. National Archives',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'bd1db39d-ef72-47c9-b6bd-da8c216e3f09',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Harare',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Zimbabwe',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n82162813',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Zimbabwe. National Archives"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Zimbabwe. National Archives',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Kimberley Africana Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'be3435df-fa2a-4599-b86a-1fc960493fba',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Kimberley',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n96084627',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Kimberley Africana Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Kimberley Africana Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'British Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'bf294dae-ae74-40da-9a9d-040182387c05',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n81139951',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"British Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'British Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Durham University Library. Special Collections',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'bf5a8b45-132f-47ac-b1db-69b399bc7eaf',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Durham',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Durham University Library. Special Collections"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Durham University Library. Special Collections',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'United Society for the Propagation of the Gospel',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'bf765ec7-12e9-4a6d-ab2b-8fd590626a1f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50064188 ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"United Society for the Propagation of the Gospel"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'United Society for the Propagation of the Gospel',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Royal Society (Great Britain)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c073bb55-5cb0-4817-9ddf-81606119f6df',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n79127772 ',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Royal Society (Great Britain)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Royal Society (Great Britain)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Library and Archives Canada',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c5500dbc-13e7-49d2-884a-1d933849186e',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Ottawa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Canada',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no2004037399',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Library and Archives Canada"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Library and Archives Canada',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Arquivo Histórico Ultramarino (Portugal)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ce2b9380-06f2-4155-8602-53a14771edb1',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Lisbon',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Portugal',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n82161807',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Arquivo Histórico Ultramarino (Portugal)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Arquivo Histórico Ultramarino (Portugal)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University of Birmingham. Library',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'en',
  'created' => 1502302657,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd00e1f00-b1f4-42b5-aa7f-7fba4efed6a8',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Birmingham',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n83137759',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/islandora/search/?f[0]=repository_ms:"University of Birmingham. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University of Birmingham. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 1,
  ),
  'url_alias' => array(),
  'date' => '2017-08-09 18:17:37 +0000',
  'user_uuid' => '22a82bbc-8b0b-4c39-99e4-a242ac324e01',
);
  $nodes[] = array(
  'title' => 'Natural History Museum (London, England). General Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd05f26a8-478c-4711-a1fe-ac22676044cc',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n95017496',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Natural History Museum (London, England). General Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Natural History Museum (London, England). General Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'New York Public Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd17bb888-bf23-43be-a68c-995698433f74',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'New York',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n79033065',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"New York Public Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'New York Public Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'New York',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Bodleian Library. Weston Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd4bb4351-9e9b-45e0-a3a8-791c14aee059',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Oxford',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Bodleian Library. Weston Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Bodleian Library. Weston Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Michigan State University. Libraries',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd56c31c2-df91-4218-bdb8-1ede9f9d82fb',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'East Lansing',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n93024323',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Michigan State University. Libraries"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Michigan State University. Libraries',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Michigan',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Dundee Central Library (Scotland)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd5cb45b7-b98d-43eb-9fc2-9ae6d3c5a54f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Dundee',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Dundee Central Library (Scotland)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Dundee Central Library (Scotland)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'St. Michael\'s All Angels Anglican Church (Harare, Zimbabwe)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd6c63bc2-ceee-4ec3-89a1-ecde61ec8684',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Harare',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Zimbabwe',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"St. Michael\'s All Angels Anglican Church (Harare, Zimbabwe)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'St. Michael\'s All Angels Anglican Church (Harare, Zimbabwe)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'University College, London. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd9d5336a-cea6-44a6-85dc-396485ae978f',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'London',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n50046126',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"University College, London. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'University College, London. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'National Library of South Africa',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e01ac006-0ef2-4d01-925b-08d13949a322',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Cape Town',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/no00023955',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"National Library of South Africa"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'National Library of South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Livingstone Memorial Parish Church (Blantyre, Scotland)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e3174cf1-3147-4be8-9843-28ec35c6b32a',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Blantyre',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Livingstone Memorial Parish Church (Blantyre, Scotland)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Livingstone Memorial Parish Church (Blantyre, Scotland)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Killie Campbell Africana Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e5dd68d3-a8e1-4c5a-87bc-e7ce69110b6b',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Durban',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'South Africa',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n80093381',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Killie Campbell Africana Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Killie Campbell Africana Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Société de géographie (France). Bibliothèque',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e7a9932c-a08f-44f4-b995-753b6bb913c4',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Paris',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'France',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Société de géographie (France). Bibliothèque"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Société de géographie (France). Bibliothèque',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Educational Resource Service Headquarters (Scotland)',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ec06735e-9d00-47b1-833a-c4f379398c98',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Hamilton',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Scotland',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Educational Resource Service Headquarters (Scotland)"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Educational Resource Service Headquarters (Scotland)',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Peter Beard Studio',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f4fc8939-418d-4c2d-a3cd-091fe4e8a54c',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'New York',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Peter Beard Studio"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Peter Beard Studio',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'New York',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Oberlin College. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f6b6d2a1-e7de-4095-8891-eadde5e91759',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Oberlin',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n85039144',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Oberlin College. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Oberlin College. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(
    'und' => array(
      0 => array(
        'value' => 'Ohio',
        'format' => NULL,
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'John Rylands University Library of Manchester',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f8283b6e-64e3-490c-ad75-0da9d2d433f7',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Manchester',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'England',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n79099353',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"John Rylands University Library of Manchester"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'John Rylands University Library of Manchester',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Sociedade de Geografia de Lisboa. Library',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'fbb30b8a-2179-4838-9ea1-1a519347b937',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Lisbon',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'Portugal',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Sociedade de Geografia de Lisboa. Library"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Sociedade de Geografia de Lisboa. Library',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  $nodes[] = array(
  'title' => 'Library of Congress. Manuscript Division',
  'log' => 'Created by FeedsNodeProcessor',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'repository_info',
  'language' => 'und',
  'created' => 1490723477,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ffcae5c2-48cc-44cc-a889-c15d019a57ba',
  'field_repo_city' => array(
    'und' => array(
      0 => array(
        'value' => 'Washington, D.C.',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_country' => array(
    'und' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_lcnaf' => array(
    'und' => array(
      0 => array(
        'value' => 'http://id.loc.gov/authorities/names/n78069648',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_link' => array(
    'und' => array(
      0 => array(
        'value' => '/in-his-own-words/catalogue/?f[0]=repository_ms:"Library of Congress. Manuscript Division"',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_repository' => array(
    'und' => array(
      0 => array(
        'value' => 'Library of Congress. Manuscript Division',
        'format' => NULL,
      ),
    ),
  ),
  'field_repo_state' => array(),
  'path' => array(
    'pathauto' => 0,
  ),
  'url_alias' => array(),
  'date' => '2017-03-28 17:51:17 +0000',
  'user_uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
);
  return $nodes;
}
