<?php

/**
 * @file
 *
 * Module imports content into Fedora from an FTP server.
 */

/**
 * Implements hook_menu().
 */
function livingstone_fedora_import_menu() {
  return array(
    'admin/livingstone/import/fedora' => array(
      'title' => 'Fedora Import',
      'description' => 'Updates and adds content from the FTP server into Fedora.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'fedora.import.form.overview.inc',
      'page callback' => 'livingstone_fedora_import_overview_menu_task',
    ),
    'admin/livingstone/import/fedora/overview' => array(
      'title' => 'Overview',
      'description' => 'Updates and adds content from the FTP server into Fedora.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'file' => 'fedora.import.form.overview.inc',
      'page callback' => 'livingstone_fedora_import_overview_menu_task',
      'weight' => -50,
    ),
    'admin/livingstone/import/fedora/local' => array(
      'title' => 'Local objects',
      'description' => 'Lists all the local objects.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_LOCAL_TASK,
      'file' => 'fedora.import.form.local.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_local_objects_form'),
      'weight' => -40,
    ),
    'admin/livingstone/import/fedora/remote' => array(
      'title' => 'Remote objects',
      'description' => 'Lists all the remote objects.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_LOCAL_TASK,
      'file' => 'fedora.import.form.remote.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_remote_objects_form'),
      'weight' => -30,
    ),
    'admin/livingstone/import/fedora/add' => array(
      'title' => 'Add',
      'description' => 'Allows the user to add new objects from the FTP.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_LOCAL_TASK,
      'file' => 'fedora.import.form.add.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_add_objects_form'),
      'weight' => -20,
    ),
    'admin/livingstone/import/fedora/update' => array(
      'title' => 'Update',
      'description' => 'Allows the user to update existing objects from the FTP.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_LOCAL_TASK,
      'file' => 'fedora.import.form.update.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_update_objects_form'),
      'weight' => 0,
    ),
    'admin/livingstone/import/fedora/remove' => array(
      'title' => 'Remove',
      'description' => 'Allows the user to remove stale objects from Fedora.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_LOCAL_TASK,
      'file' => 'fedora.import.form.remove.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_remove_objects_form'),
      'weight' => 0,
    ),
    'admin/livingstone/import/fedora/publish' => array(
      'title' => 'Publish / Conceal',
      'description' => 'Allows the user to publish/hide objects in Fedora.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_LOCAL_TASK,
      'file' => 'fedora.import.form.publish.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_publish_objects_form'),
      'weight' => 10,
    ),
    'admin/livingstone/import/fedora/errors' => array(
      'title' => 'Error Log',
      'description' => 'Lists any errors that have occurred during import.',
      'access arguments' => array(LIVINGSTONE_ADMINISTER_PERMISSION),
      'type' => MENU_LOCAL_TASK,
      'file' => 'fedora.import.form.error.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_fedora_import_error_form'),
      'weight' => 20,
    ),
  );
}