/*! URI.js v1.17.1 http://medialize.github.io/URI.js/ */
/* build contains: URI.js, URITemplate.js, jquery.URI.js */
(function(f,h){"object"===typeof exports?module.exports=h(require("./punycode"),require("./IPv6"),require("./SecondLevelDomains")):"function"===typeof define&&define.amd?define(["./punycode","./IPv6","./SecondLevelDomains"],h):f.URI=h(f.punycode,f.IPv6,f.SecondLevelDomains,f)})(this,function(f,h,t,u){function c(a,b){var d=1<=arguments.length,m=2<=arguments.length;if(!(this instanceof c))return d?m?new c(a,b):new c(a):new c;if(void 0===a){if(d)throw new TypeError("undefined is not a valid argument for URI");
a="undefined"!==typeof location?location.href+"":""}this.href(a);return void 0!==b?this.absoluteTo(b):this}function y(a){return a.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")}function z(a){return void 0===a?"Undefined":String(Object.prototype.toString.call(a)).slice(8,-1)}function r(a){return"Array"===z(a)}function p(a,b){var d={},c,x;if("RegExp"===z(b))d=null;else if(r(b))for(c=0,x=b.length;c<x;c++)d[b[c]]=!0;else d[b]=!0;c=0;for(x=a.length;c<x;c++)if(d&&void 0!==d[a[c]]||!d&&b.test(a[c]))a.splice(c,
1),x--,c--;return a}function w(a,b){var d,c;if(r(b)){d=0;for(c=b.length;d<c;d++)if(!w(a,b[d]))return!1;return!0}var x=z(b);d=0;for(c=a.length;d<c;d++)if("RegExp"===x){if("string"===typeof a[d]&&a[d].match(b))return!0}else if(a[d]===b)return!0;return!1}function C(a,b){if(!r(a)||!r(b)||a.length!==b.length)return!1;a.sort();b.sort();for(var d=0,c=a.length;d<c;d++)if(a[d]!==b[d])return!1;return!0}function g(a){return a.replace(/^\/+|\/+$/g,"")}function k(a){return escape(a)}function q(a){return encodeURIComponent(a).replace(/[!'()*]/g,
k).replace(/\*/g,"%2A")}function l(a){return function(b,d){if(void 0===b)return this._parts[a]||"";this._parts[a]=b||null;this.build(!d);return this}}function n(a,b){return function(d,c){if(void 0===d)return this._parts[a]||"";null!==d&&(d+="",d.charAt(0)===b&&(d=d.substring(1)));this._parts[a]=d;this.build(!c);return this}}var E=u&&u.URI;c.version="1.17.1";var e=c.prototype,v=Object.prototype.hasOwnProperty;c._parts=function(){return{protocol:null,username:null,password:null,hostname:null,urn:null,
port:null,path:null,query:null,fragment:null,duplicateQueryParameters:c.duplicateQueryParameters,escapeQuerySpace:c.escapeQuerySpace}};c.duplicateQueryParameters=!1;c.escapeQuerySpace=!0;c.protocol_expression=/^[a-z][a-z0-9.+-]*$/i;c.idn_expression=/[^a-z0-9\.-]/i;c.punycode_expression=/(xn--)/i;c.ip4_expression=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;c.ip6_expression=/^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/;
c.find_uri_expression=/\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))/ig;c.findUri={start:/\b(?:([a-z][a-z0-9.+-]*:\/\/)|www\.)/gi,end:/[\s\r\n]|$/,trim:/[`!()\[\]{};:'".,<>?\u00ab\u00bb\u201c\u201d\u201e\u2018\u2019]+$/};c.defaultPorts={http:"80",https:"443",ftp:"21",gopher:"70",ws:"80",wss:"443"};c.invalid_hostname_characters=
/[^a-zA-Z0-9\.-]/;c.domAttributes={a:"href",blockquote:"cite",link:"href",base:"href",script:"src",form:"action",img:"src",area:"href",iframe:"src",embed:"src",source:"src",track:"src",input:"src",audio:"src",video:"src"};c.getDomAttribute=function(a){if(a&&a.nodeName){var b=a.nodeName.toLowerCase();return"input"===b&&"image"!==a.type?void 0:c.domAttributes[b]}};c.encode=q;c.decode=decodeURIComponent;c.iso8859=function(){c.encode=escape;c.decode=unescape};c.unicode=function(){c.encode=q;c.decode=
decodeURIComponent};c.characters={pathname:{encode:{expression:/%(24|26|2B|2C|3B|3D|3A|40)/ig,map:{"%24":"$","%26":"&","%2B":"+","%2C":",","%3B":";","%3D":"=","%3A":":","%40":"@"}},decode:{expression:/[\/\?#]/g,map:{"/":"%2F","?":"%3F","#":"%23"}}},reserved:{encode:{expression:/%(21|23|24|26|27|28|29|2A|2B|2C|2F|3A|3B|3D|3F|40|5B|5D)/ig,map:{"%3A":":","%2F":"/","%3F":"?","%23":"#","%5B":"[","%5D":"]","%40":"@","%21":"!","%24":"$","%26":"&","%27":"'","%28":"(","%29":")","%2A":"*","%2B":"+","%2C":",",
"%3B":";","%3D":"="}}},urnpath:{encode:{expression:/%(21|24|27|28|29|2A|2B|2C|3B|3D|40)/ig,map:{"%21":"!","%24":"$","%27":"'","%28":"(","%29":")","%2A":"*","%2B":"+","%2C":",","%3B":";","%3D":"=","%40":"@"}},decode:{expression:/[\/\?#:]/g,map:{"/":"%2F","?":"%3F","#":"%23",":":"%3A"}}}};c.encodeQuery=function(a,b){var d=c.encode(a+"");void 0===b&&(b=c.escapeQuerySpace);return b?d.replace(/%20/g,"+"):d};c.decodeQuery=function(a,b){a+="";void 0===b&&(b=c.escapeQuerySpace);try{return c.decode(b?a.replace(/\+/g,
"%20"):a)}catch(d){return a}};var A={encode:"encode",decode:"decode"},B,D=function(a,b){return function(d){try{return c[b](d+"").replace(c.characters[a][b].expression,function(d){return c.characters[a][b].map[d]})}catch(m){return d}}};for(B in A)c[B+"PathSegment"]=D("pathname",A[B]),c[B+"UrnPathSegment"]=D("urnpath",A[B]);A=function(a,b,d){return function(m){var x;x=d?function(a){return c[b](c[d](a))}:c[b];m=(m+"").split(a);for(var e=0,g=m.length;e<g;e++)m[e]=x(m[e]);return m.join(a)}};c.decodePath=
A("/","decodePathSegment");c.decodeUrnPath=A(":","decodeUrnPathSegment");c.recodePath=A("/","encodePathSegment","decode");c.recodeUrnPath=A(":","encodeUrnPathSegment","decode");c.encodeReserved=D("reserved","encode");c.parse=function(a,b){var d;b||(b={});d=a.indexOf("#");-1<d&&(b.fragment=a.substring(d+1)||null,a=a.substring(0,d));d=a.indexOf("?");-1<d&&(b.query=a.substring(d+1)||null,a=a.substring(0,d));"//"===a.substring(0,2)?(b.protocol=null,a=a.substring(2),a=c.parseAuthority(a,b)):(d=a.indexOf(":"),
-1<d&&(b.protocol=a.substring(0,d)||null,b.protocol&&!b.protocol.match(c.protocol_expression)?b.protocol=void 0:"//"===a.substring(d+1,d+3)?(a=a.substring(d+3),a=c.parseAuthority(a,b)):(a=a.substring(d+1),b.urn=!0)));b.path=a;return b};c.parseHost=function(a,b){a=a.replace(/\\/g,"/");var d=a.indexOf("/"),c;-1===d&&(d=a.length);if("["===a.charAt(0))c=a.indexOf("]"),b.hostname=a.substring(1,c)||null,b.port=a.substring(c+2,d)||null,"/"===b.port&&(b.port=null);else{var x=a.indexOf(":");c=a.indexOf("/");
x=a.indexOf(":",x+1);-1!==x&&(-1===c||x<c)?(b.hostname=a.substring(0,d)||null,b.port=null):(c=a.substring(0,d).split(":"),b.hostname=c[0]||null,b.port=c[1]||null)}b.hostname&&"/"!==a.substring(d).charAt(0)&&(d++,a="/"+a);return a.substring(d)||"/"};c.parseAuthority=function(a,b){a=c.parseUserinfo(a,b);return c.parseHost(a,b)};c.parseUserinfo=function(a,b){var d=a.indexOf("/"),m=a.lastIndexOf("@",-1<d?d:a.length-1);-1<m&&(-1===d||m<d)?(d=a.substring(0,m).split(":"),b.username=d[0]?c.decode(d[0]):null,
d.shift(),b.password=d[0]?c.decode(d.join(":")):null,a=a.substring(m+1)):(b.username=null,b.password=null);return a};c.parseQuery=function(a,b){if(!a)return{};a=a.replace(/&+/g,"&").replace(/^\?*&*|&+$/g,"");if(!a)return{};for(var d={},m=a.split("&"),x=m.length,e,g,p=0;p<x;p++)if(e=m[p].split("="),g=c.decodeQuery(e.shift(),b),e=e.length?c.decodeQuery(e.join("="),b):null,v.call(d,g)){if("string"===typeof d[g]||null===d[g])d[g]=[d[g]];d[g].push(e)}else d[g]=e;return d};c.build=function(a){var b="";
a.protocol&&(b+=a.protocol+":");a.urn||!b&&!a.hostname||(b+="//");b+=c.buildAuthority(a)||"";"string"===typeof a.path&&("/"!==a.path.charAt(0)&&"string"===typeof a.hostname&&(b+="/"),b+=a.path);"string"===typeof a.query&&a.query&&(b+="?"+a.query);"string"===typeof a.fragment&&a.fragment&&(b+="#"+a.fragment);return b};c.buildHost=function(a){var b="";if(a.hostname)b=c.ip6_expression.test(a.hostname)?b+("["+a.hostname+"]"):b+a.hostname;else return"";a.port&&(b+=":"+a.port);return b};c.buildAuthority=
function(a){return c.buildUserinfo(a)+c.buildHost(a)};c.buildUserinfo=function(a){var b="";a.username&&(b+=c.encode(a.username),a.password&&(b+=":"+c.encode(a.password)),b+="@");return b};c.buildQuery=function(a,b,d){var m="",e,g,p,k;for(g in a)if(v.call(a,g)&&g)if(r(a[g]))for(e={},p=0,k=a[g].length;p<k;p++)void 0!==a[g][p]&&void 0===e[a[g][p]+""]&&(m+="&"+c.buildQueryParameter(g,a[g][p],d),!0!==b&&(e[a[g][p]+""]=!0));else void 0!==a[g]&&(m+="&"+c.buildQueryParameter(g,a[g],d));return m.substring(1)};
c.buildQueryParameter=function(a,b,d){return c.encodeQuery(a,d)+(null!==b?"="+c.encodeQuery(b,d):"")};c.addQuery=function(a,b,d){if("object"===typeof b)for(var m in b)v.call(b,m)&&c.addQuery(a,m,b[m]);else if("string"===typeof b)void 0===a[b]?a[b]=d:("string"===typeof a[b]&&(a[b]=[a[b]]),r(d)||(d=[d]),a[b]=(a[b]||[]).concat(d));else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");};c.removeQuery=function(a,b,d){var m;if(r(b))for(d=0,m=b.length;d<m;d++)a[b[d]]=
void 0;else if("RegExp"===z(b))for(m in a)b.test(m)&&(a[m]=void 0);else if("object"===typeof b)for(m in b)v.call(b,m)&&c.removeQuery(a,m,b[m]);else if("string"===typeof b)void 0!==d?"RegExp"===z(d)?!r(a[b])&&d.test(a[b])?a[b]=void 0:a[b]=p(a[b],d):a[b]!==String(d)||r(d)&&1!==d.length?r(a[b])&&(a[b]=p(a[b],d)):a[b]=void 0:a[b]=void 0;else throw new TypeError("URI.removeQuery() accepts an object, string, RegExp as the first parameter");};c.hasQuery=function(a,b,d,m){switch(z(b)){case "String":break;
case "RegExp":for(var e in a)if(v.call(a,e)&&b.test(e)&&(void 0===d||c.hasQuery(a,e,d)))return!0;return!1;case "Object":for(var g in b)if(v.call(b,g)&&!c.hasQuery(a,g,b[g]))return!1;return!0;default:throw new TypeError("URI.hasQuery() accepts a string, regular expression or object as the name parameter");}switch(z(d)){case "Undefined":return b in a;case "Boolean":return a=!(r(a[b])?!a[b].length:!a[b]),d===a;case "Function":return!!d(a[b],b,a);case "Array":return r(a[b])?(m?w:C)(a[b],d):!1;case "RegExp":return r(a[b])?
m?w(a[b],d):!1:!(!a[b]||!a[b].match(d));case "Number":d=String(d);case "String":return r(a[b])?m?w(a[b],d):!1:a[b]===d;default:throw new TypeError("URI.hasQuery() accepts undefined, boolean, string, number, RegExp, Function as the value parameter");}};c.commonPath=function(a,b){var d=Math.min(a.length,b.length),c;for(c=0;c<d;c++)if(a.charAt(c)!==b.charAt(c)){c--;break}if(1>c)return a.charAt(0)===b.charAt(0)&&"/"===a.charAt(0)?"/":"";if("/"!==a.charAt(c)||"/"!==b.charAt(c))c=a.substring(0,c).lastIndexOf("/");
return a.substring(0,c+1)};c.withinString=function(a,b,d){d||(d={});var m=d.start||c.findUri.start,e=d.end||c.findUri.end,g=d.trim||c.findUri.trim,p=/[a-z0-9-]=["']?$/i;for(m.lastIndex=0;;){var k=m.exec(a);if(!k)break;k=k.index;if(d.ignoreHtml){var q=a.slice(Math.max(k-3,0),k);if(q&&p.test(q))continue}var q=k+a.slice(k).search(e),l=a.slice(k,q).replace(g,"");d.ignore&&d.ignore.test(l)||(q=k+l.length,l=b(l,k,q,a),a=a.slice(0,k)+l+a.slice(q),m.lastIndex=k+l.length)}m.lastIndex=0;return a};c.ensureValidHostname=
function(a){if(a.match(c.invalid_hostname_characters)){if(!f)throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-] and Punycode.js is not available');if(f.toASCII(a).match(c.invalid_hostname_characters))throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-]');}};c.noConflict=function(a){if(a)return a={URI:this.noConflict()},u.URITemplate&&"function"===typeof u.URITemplate.noConflict&&(a.URITemplate=u.URITemplate.noConflict()),u.IPv6&&"function"===
typeof u.IPv6.noConflict&&(a.IPv6=u.IPv6.noConflict()),u.SecondLevelDomains&&"function"===typeof u.SecondLevelDomains.noConflict&&(a.SecondLevelDomains=u.SecondLevelDomains.noConflict()),a;u.URI===this&&(u.URI=E);return this};e.build=function(a){if(!0===a)this._deferred_build=!0;else if(void 0===a||this._deferred_build)this._string=c.build(this._parts),this._deferred_build=!1;return this};e.clone=function(){return new c(this)};e.valueOf=e.toString=function(){return this.build(!1)._string};e.protocol=
l("protocol");e.username=l("username");e.password=l("password");e.hostname=l("hostname");e.port=l("port");e.query=n("query","?");e.fragment=n("fragment","#");e.search=function(a,b){var d=this.query(a,b);return"string"===typeof d&&d.length?"?"+d:d};e.hash=function(a,b){var d=this.fragment(a,b);return"string"===typeof d&&d.length?"#"+d:d};e.pathname=function(a,b){if(void 0===a||!0===a){var d=this._parts.path||(this._parts.hostname?"/":"");return a?(this._parts.urn?c.decodeUrnPath:c.decodePath)(d):d}this._parts.path=
this._parts.urn?a?c.recodeUrnPath(a):"":a?c.recodePath(a):"/";this.build(!b);return this};e.path=e.pathname;e.href=function(a,b){var d;if(void 0===a)return this.toString();this._string="";this._parts=c._parts();var m=a instanceof c,e="object"===typeof a&&(a.hostname||a.path||a.pathname);a.nodeName&&(e=c.getDomAttribute(a),a=a[e]||"",e=!1);!m&&e&&void 0!==a.pathname&&(a=a.toString());if("string"===typeof a||a instanceof String)this._parts=c.parse(String(a),this._parts);else if(m||e)for(d in m=m?a._parts:
a,m)v.call(this._parts,d)&&(this._parts[d]=m[d]);else throw new TypeError("invalid input");this.build(!b);return this};e.is=function(a){var b=!1,d=!1,m=!1,e=!1,g=!1,p=!1,k=!1,q=!this._parts.urn;this._parts.hostname&&(q=!1,d=c.ip4_expression.test(this._parts.hostname),m=c.ip6_expression.test(this._parts.hostname),b=d||m,g=(e=!b)&&t&&t.has(this._parts.hostname),p=e&&c.idn_expression.test(this._parts.hostname),k=e&&c.punycode_expression.test(this._parts.hostname));switch(a.toLowerCase()){case "relative":return q;
case "absolute":return!q;case "domain":case "name":return e;case "sld":return g;case "ip":return b;case "ip4":case "ipv4":case "inet4":return d;case "ip6":case "ipv6":case "inet6":return m;case "idn":return p;case "url":return!this._parts.urn;case "urn":return!!this._parts.urn;case "punycode":return k}return null};var F=e.protocol,G=e.port,H=e.hostname;e.protocol=function(a,b){if(void 0!==a&&a&&(a=a.replace(/:(\/\/)?$/,""),!a.match(c.protocol_expression)))throw new TypeError('Protocol "'+a+"\" contains characters other than [A-Z0-9.+-] or doesn't start with [A-Z]");
return F.call(this,a,b)};e.scheme=e.protocol;e.port=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0!==a&&(0===a&&(a=null),a&&(a+="",":"===a.charAt(0)&&(a=a.substring(1)),a.match(/[^0-9]/))))throw new TypeError('Port "'+a+'" contains characters other than [0-9]');return G.call(this,a,b)};e.hostname=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0!==a){var d={};if("/"!==c.parseHost(a,d))throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-]');
a=d.hostname}return H.call(this,a,b)};e.origin=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a){var d=this.protocol();return this.authority()?(d?d+"://":"")+this.authority():""}d=c(a);this.protocol(d.protocol()).authority(d.authority()).build(!b);return this};e.host=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a)return this._parts.hostname?c.buildHost(this._parts):"";if("/"!==c.parseHost(a,this._parts))throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-]');
this.build(!b);return this};e.authority=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a)return this._parts.hostname?c.buildAuthority(this._parts):"";if("/"!==c.parseAuthority(a,this._parts))throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-]');this.build(!b);return this};e.userinfo=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a){if(!this._parts.username)return"";var d=c.buildUserinfo(this._parts);return d.substring(0,d.length-
1)}"@"!==a[a.length-1]&&(a+="@");c.parseUserinfo(a,this._parts);this.build(!b);return this};e.resource=function(a,b){var d;if(void 0===a)return this.path()+this.search()+this.hash();d=c.parse(a);this._parts.path=d.path;this._parts.query=d.query;this._parts.fragment=d.fragment;this.build(!b);return this};e.subdomain=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";var d=this._parts.hostname.length-this.domain().length-1;return this._parts.hostname.substring(0,
d)||""}d=this._parts.hostname.length-this.domain().length;d=this._parts.hostname.substring(0,d);d=new RegExp("^"+y(d));a&&"."!==a.charAt(a.length-1)&&(a+=".");a&&c.ensureValidHostname(a);this._parts.hostname=this._parts.hostname.replace(d,a);this.build(!b);return this};e.domain=function(a,b){if(this._parts.urn)return void 0===a?"":this;"boolean"===typeof a&&(b=a,a=void 0);if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";var d=this._parts.hostname.match(/\./g);if(d&&2>d.length)return this._parts.hostname;
d=this._parts.hostname.length-this.tld(b).length-1;d=this._parts.hostname.lastIndexOf(".",d-1)+1;return this._parts.hostname.substring(d)||""}if(!a)throw new TypeError("cannot set domain empty");c.ensureValidHostname(a);!this._parts.hostname||this.is("IP")?this._parts.hostname=a:(d=new RegExp(y(this.domain())+"$"),this._parts.hostname=this._parts.hostname.replace(d,a));this.build(!b);return this};e.tld=function(a,b){if(this._parts.urn)return void 0===a?"":this;"boolean"===typeof a&&(b=a,a=void 0);
if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";var d=this._parts.hostname.lastIndexOf("."),d=this._parts.hostname.substring(d+1);return!0!==b&&t&&t.list[d.toLowerCase()]?t.get(this._parts.hostname)||d:d}if(a)if(a.match(/[^a-zA-Z0-9-]/))if(t&&t.is(a))d=new RegExp(y(this.tld())+"$"),this._parts.hostname=this._parts.hostname.replace(d,a);else throw new TypeError('TLD "'+a+'" contains characters other than [A-Z0-9]');else{if(!this._parts.hostname||this.is("IP"))throw new ReferenceError("cannot set TLD on non-domain host");
d=new RegExp(y(this.tld())+"$");this._parts.hostname=this._parts.hostname.replace(d,a)}else throw new TypeError("cannot set TLD empty");this.build(!b);return this};e.directory=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path&&!this._parts.hostname)return"";if("/"===this._parts.path)return"/";var d=this._parts.path.length-this.filename().length-1,d=this._parts.path.substring(0,d)||(this._parts.hostname?"/":"");return a?c.decodePath(d):d}d=this._parts.path.length-
this.filename().length;d=this._parts.path.substring(0,d);d=new RegExp("^"+y(d));this.is("relative")||(a||(a="/"),"/"!==a.charAt(0)&&(a="/"+a));a&&"/"!==a.charAt(a.length-1)&&(a+="/");a=c.recodePath(a);this._parts.path=this._parts.path.replace(d,a);this.build(!b);return this};e.filename=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";var d=this._parts.path.lastIndexOf("/"),d=this._parts.path.substring(d+1);return a?
c.decodePathSegment(d):d}d=!1;"/"===a.charAt(0)&&(a=a.substring(1));a.match(/\.?\//)&&(d=!0);var e=new RegExp(y(this.filename())+"$");a=c.recodePath(a);this._parts.path=this._parts.path.replace(e,a);d?this.normalizePath(b):this.build(!b);return this};e.suffix=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";var d=this.filename(),e=d.lastIndexOf(".");if(-1===e)return"";d=d.substring(e+1);d=/^[a-z0-9%]+$/i.test(d)?
d:"";return a?c.decodePathSegment(d):d}"."===a.charAt(0)&&(a=a.substring(1));if(d=this.suffix())e=a?new RegExp(y(d)+"$"):new RegExp(y("."+d)+"$");else{if(!a)return this;this._parts.path+="."+c.recodePath(a)}e&&(a=c.recodePath(a),this._parts.path=this._parts.path.replace(e,a));this.build(!b);return this};e.segment=function(a,b,d){var c=this._parts.urn?":":"/",e=this.path(),p="/"===e.substring(0,1),e=e.split(c);void 0!==a&&"number"!==typeof a&&(d=b,b=a,a=void 0);if(void 0!==a&&"number"!==typeof a)throw Error('Bad segment "'+
a+'", must be 0-based integer');p&&e.shift();0>a&&(a=Math.max(e.length+a,0));if(void 0===b)return void 0===a?e:e[a];if(null===a||void 0===e[a])if(r(b)){e=[];a=0;for(var k=b.length;a<k;a++)if(b[a].length||e.length&&e[e.length-1].length)e.length&&!e[e.length-1].length&&e.pop(),e.push(g(b[a]))}else{if(b||"string"===typeof b)b=g(b),""===e[e.length-1]?e[e.length-1]=b:e.push(b)}else b?e[a]=g(b):e.splice(a,1);p&&e.unshift("");return this.path(e.join(c),d)};e.segmentCoded=function(a,b,d){var e,g;"number"!==
typeof a&&(d=b,b=a,a=void 0);if(void 0===b){a=this.segment(a,b,d);if(r(a))for(e=0,g=a.length;e<g;e++)a[e]=c.decode(a[e]);else a=void 0!==a?c.decode(a):void 0;return a}if(r(b))for(e=0,g=b.length;e<g;e++)b[e]=c.encode(b[e]);else b="string"===typeof b||b instanceof String?c.encode(b):b;return this.segment(a,b,d)};var I=e.query;e.query=function(a,b){if(!0===a)return c.parseQuery(this._parts.query,this._parts.escapeQuerySpace);if("function"===typeof a){var d=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace),
e=a.call(this,d);this._parts.query=c.buildQuery(e||d,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);this.build(!b);return this}return void 0!==a&&"string"!==typeof a?(this._parts.query=c.buildQuery(a,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace),this.build(!b),this):I.call(this,a,b)};e.setQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace);if("string"===typeof a||a instanceof String)e[a]=void 0!==b?b:null;else if("object"===
typeof a)for(var g in a)v.call(a,g)&&(e[g]=a[g]);else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");this._parts.query=c.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(d=b);this.build(!d);return this};e.addQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace);c.addQuery(e,a,void 0===b?null:b);this._parts.query=c.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);
"string"!==typeof a&&(d=b);this.build(!d);return this};e.removeQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace);c.removeQuery(e,a,b);this._parts.query=c.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(d=b);this.build(!d);return this};e.hasQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace);return c.hasQuery(e,a,b,d)};e.setSearch=e.setQuery;e.addSearch=e.addQuery;e.removeSearch=
e.removeQuery;e.hasSearch=e.hasQuery;e.normalize=function(){return this._parts.urn?this.normalizeProtocol(!1).normalizePath(!1).normalizeQuery(!1).normalizeFragment(!1).build():this.normalizeProtocol(!1).normalizeHostname(!1).normalizePort(!1).normalizePath(!1).normalizeQuery(!1).normalizeFragment(!1).build()};e.normalizeProtocol=function(a){"string"===typeof this._parts.protocol&&(this._parts.protocol=this._parts.protocol.toLowerCase(),this.build(!a));return this};e.normalizeHostname=function(a){this._parts.hostname&&
(this.is("IDN")&&f?this._parts.hostname=f.toASCII(this._parts.hostname):this.is("IPv6")&&h&&(this._parts.hostname=h.best(this._parts.hostname)),this._parts.hostname=this._parts.hostname.toLowerCase(),this.build(!a));return this};e.normalizePort=function(a){"string"===typeof this._parts.protocol&&this._parts.port===c.defaultPorts[this._parts.protocol]&&(this._parts.port=null,this.build(!a));return this};e.normalizePath=function(a){var b=this._parts.path;if(!b)return this;if(this._parts.urn)return this._parts.path=
c.recodeUrnPath(this._parts.path),this.build(!a),this;if("/"===this._parts.path)return this;var b=c.recodePath(b),d,e="",g,p;"/"!==b.charAt(0)&&(d=!0,b="/"+b);if("/.."===b.slice(-3)||"/."===b.slice(-2))b+="/";b=b.replace(/(\/(\.\/)+)|(\/\.$)/g,"/").replace(/\/{2,}/g,"/");d&&(e=b.substring(1).match(/^(\.\.\/)+/)||"")&&(e=e[0]);for(;;){g=b.search(/\/\.\.(\/|$)/);if(-1===g)break;else if(0===g){b=b.substring(3);continue}p=b.substring(0,g).lastIndexOf("/");-1===p&&(p=g);b=b.substring(0,p)+b.substring(g+
3)}d&&this.is("relative")&&(b=e+b.substring(1));this._parts.path=b;this.build(!a);return this};e.normalizePathname=e.normalizePath;e.normalizeQuery=function(a){"string"===typeof this._parts.query&&(this._parts.query.length?this.query(c.parseQuery(this._parts.query,this._parts.escapeQuerySpace)):this._parts.query=null,this.build(!a));return this};e.normalizeFragment=function(a){this._parts.fragment||(this._parts.fragment=null,this.build(!a));return this};e.normalizeSearch=e.normalizeQuery;e.normalizeHash=
e.normalizeFragment;e.iso8859=function(){var a=c.encode,b=c.decode;c.encode=escape;c.decode=decodeURIComponent;try{this.normalize()}finally{c.encode=a,c.decode=b}return this};e.unicode=function(){var a=c.encode,b=c.decode;c.encode=q;c.decode=unescape;try{this.normalize()}finally{c.encode=a,c.decode=b}return this};e.readable=function(){var a=this.clone();a.username("").password("").normalize();var b="";a._parts.protocol&&(b+=a._parts.protocol+"://");a._parts.hostname&&(a.is("punycode")&&f?(b+=f.toUnicode(a._parts.hostname),
a._parts.port&&(b+=":"+a._parts.port)):b+=a.host());a._parts.hostname&&a._parts.path&&"/"!==a._parts.path.charAt(0)&&(b+="/");b+=a.path(!0);if(a._parts.query){for(var d="",e=0,g=a._parts.query.split("&"),p=g.length;e<p;e++){var k=(g[e]||"").split("="),d=d+("&"+c.decodeQuery(k[0],this._parts.escapeQuerySpace).replace(/&/g,"%26"));void 0!==k[1]&&(d+="="+c.decodeQuery(k[1],this._parts.escapeQuerySpace).replace(/&/g,"%26"))}b+="?"+d.substring(1)}return b+=c.decodeQuery(a.hash(),!0)};e.absoluteTo=function(a){var b=
this.clone(),d=["protocol","username","password","hostname","port"],e,g;if(this._parts.urn)throw Error("URNs do not have any generally defined hierarchical components");a instanceof c||(a=new c(a));b._parts.protocol||(b._parts.protocol=a._parts.protocol);if(this._parts.hostname)return b;for(e=0;g=d[e];e++)b._parts[g]=a._parts[g];b._parts.path?".."===b._parts.path.substring(-2)&&(b._parts.path+="/"):(b._parts.path=a._parts.path,b._parts.query||(b._parts.query=a._parts.query));"/"!==b.path().charAt(0)&&
(d=(d=a.directory())?d:0===a.path().indexOf("/")?"/":"",b._parts.path=(d?d+"/":"")+b._parts.path,b.normalizePath());b.build();return b};e.relativeTo=function(a){var b=this.clone().normalize(),d,e,g;if(b._parts.urn)throw Error("URNs do not have any generally defined hierarchical components");a=(new c(a)).normalize();d=b._parts;e=a._parts;g=b.path();a=a.path();if("/"!==g.charAt(0))throw Error("URI is already relative");if("/"!==a.charAt(0))throw Error("Cannot calculate a URI relative to another relative URI");
d.protocol===e.protocol&&(d.protocol=null);if(d.username===e.username&&d.password===e.password&&null===d.protocol&&null===d.username&&null===d.password&&d.hostname===e.hostname&&d.port===e.port)d.hostname=null,d.port=null;else return b.build();if(g===a)return d.path="",b.build();g=c.commonPath(g,a);if(!g)return b.build();e=e.path.substring(g.length).replace(/[^\/]*$/,"").replace(/.*?\//g,"../");d.path=e+d.path.substring(g.length)||"./";return b.build()};e.equals=function(a){var b=this.clone();a=new c(a);
var d={},e={},g={},p;b.normalize();a.normalize();if(b.toString()===a.toString())return!0;d=b.query();e=a.query();b.query("");a.query("");if(b.toString()!==a.toString()||d.length!==e.length)return!1;d=c.parseQuery(d,this._parts.escapeQuerySpace);e=c.parseQuery(e,this._parts.escapeQuerySpace);for(p in d)if(v.call(d,p)){if(!r(d[p])){if(d[p]!==e[p])return!1}else if(!C(d[p],e[p]))return!1;g[p]=!0}for(p in e)if(v.call(e,p)&&!g[p])return!1;return!0};e.duplicateQueryParameters=function(a){this._parts.duplicateQueryParameters=
!!a;return this};e.escapeQuerySpace=function(a){this._parts.escapeQuerySpace=!!a;return this};return c});
(function(f,h){"object"===typeof exports?module.exports=h(require("./URI")):"function"===typeof define&&define.amd?define(["./URI"],h):f.URITemplate=h(f.URI,f)})(this,function(f, h){function t(c){if(t._cache[c])return t._cache[c];if(!(this instanceof t))return new t(c);this.expression=c;t._cache[c]=this;return this}function u(c){this.data=c;this.cache={}}var c=h&&h.URITemplate,y=Object.prototype.hasOwnProperty,z=t.prototype,r={"":{prefix:"",separator:",",named:!1,empty_name_separator:!1,encode:"encode"},
"+":{prefix:"",separator:",",named:!1,empty_name_separator:!1,encode:"encodeReserved"},"#":{prefix:"#",separator:",",named:!1,empty_name_separator:!1,encode:"encodeReserved"},".":{prefix:".",separator:".",named:!1,empty_name_separator:!1,encode:"encode"},"/":{prefix:"/",separator:"/",named:!1,empty_name_separator:!1,encode:"encode"},";":{prefix:";",separator:";",named:!0,empty_name_separator:!1,encode:"encode"},"?":{prefix:"?",separator:"&",named:!0,empty_name_separator:!0,encode:"encode"},"&":{prefix:"&",
separator:"&",named:!0,empty_name_separator:!0,encode:"encode"}};t._cache={};t.EXPRESSION_PATTERN=/\{([^a-zA-Z0-9%_]?)([^\}]+)(\}|$)/g;t.VARIABLE_PATTERN=/^([^*:]+)((\*)|:(\d+))?$/;t.VARIABLE_NAME_PATTERN=/[^a-zA-Z0-9%_]/;t.expand=function(c,w){var f=r[c.operator],g=f.named?"Named":"Unnamed",k=c.variables,q=[],l,n,h;for(h=0;n=k[h];h++)l=w.get(n.name),l.val.length?q.push(t["expand"+g](l,f,n.explode,n.explode&&f.separator||",",n.maxlength,n.name)):l.type&&q.push("");return q.length?f.prefix+q.join(f.separator):
""};t.expandNamed=function(c,w,t,g,k,q){var l="",n=w.encode;w=w.empty_name_separator;var h=!c[n].length,e=2===c.type?"":f[n](q),v,r,u;r=0;for(u=c.val.length;r<u;r++)k?(v=f[n](c.val[r][1].substring(0,k)),2===c.type&&(e=f[n](c.val[r][0].substring(0,k)))):h?(v=f[n](c.val[r][1]),2===c.type?(e=f[n](c.val[r][0]),c[n].push([e,v])):c[n].push([void 0,v])):(v=c[n][r][1],2===c.type&&(e=c[n][r][0])),l&&(l+=g),t?l+=e+(w||v?"=":"")+v:(r||(l+=f[n](q)+(w||v?"=":"")),2===c.type&&(l+=e+","),l+=v);return l};t.expandUnnamed=
function(c,w,t,g,k){var q="",l=w.encode;w=w.empty_name_separator;var n=!c[l].length,r,e,h,u;h=0;for(u=c.val.length;h<u;h++)k?e=f[l](c.val[h][1].substring(0,k)):n?(e=f[l](c.val[h][1]),c[l].push([2===c.type?f[l](c.val[h][0]):void 0,e])):e=c[l][h][1],q&&(q+=g),2===c.type&&(r=k?f[l](c.val[h][0].substring(0,k)):c[l][h][0],q+=r,q=t?q+(w||e?"=":""):q+","),q+=e;return q};t.noConflict=function(){h.URITemplate===t&&(h.URITemplate=c);return t};z.expand=function(c){var f="";this.parts&&this.parts.length||this.parse();
c instanceof u||(c=new u(c));for(var h=0,g=this.parts.length;h<g;h++)f+="string"===typeof this.parts[h]?this.parts[h]:t.expand(this.parts[h],c);return f};z.parse=function(){var c=this.expression,f=t.EXPRESSION_PATTERN,h=t.VARIABLE_PATTERN,g=t.VARIABLE_NAME_PATTERN,k=[],q=0,l,n,u;for(f.lastIndex=0;;){n=f.exec(c);if(null===n){k.push(c.substring(q));break}else k.push(c.substring(q,n.index)),q=n.index+n[0].length;if(!r[n[1]])throw Error('Unknown Operator "'+n[1]+'" in "'+n[0]+'"');if(!n[3])throw Error('Unclosed Expression "'+
n[0]+'"');l=n[2].split(",");for(var e=0,v=l.length;e<v;e++){u=l[e].match(h);if(null===u)throw Error('Invalid Variable "'+l[e]+'" in "'+n[0]+'"');if(u[1].match(g))throw Error('Invalid Variable Name "'+u[1]+'" in "'+n[0]+'"');l[e]={name:u[1],explode:!!u[3],maxlength:u[4]&&parseInt(u[4],10)}}if(!l.length)throw Error('Expression Missing Variable(s) "'+n[0]+'"');k.push({expression:n[0],operator:n[1],variables:l})}k.length||k.push(c);this.parts=k;return this};u.prototype.get=function(c){var f=this.data,
h={type:0,val:[],encode:[],encodeReserved:[]},g;if(void 0!==this.cache[c])return this.cache[c];this.cache[c]=h;f="[object Function]"===String(Object.prototype.toString.call(f))?f(c):"[object Function]"===String(Object.prototype.toString.call(f[c]))?f[c](c):f[c];if(void 0!==f&&null!==f)if("[object Array]"===String(Object.prototype.toString.call(f))){g=0;for(c=f.length;g<c;g++)void 0!==f[g]&&null!==f[g]&&h.val.push([void 0,String(f[g])]);h.val.length&&(h.type=3)}else if("[object Object]"===String(Object.prototype.toString.call(f))){for(g in f)y.call(f,
g)&&void 0!==f[g]&&null!==f[g]&&h.val.push([g,String(f[g])]);h.val.length&&(h.type=2)}else h.type=1,h.val.push([void 0,String(f)]);return h};f.expand=function(c,h){var r=(new t(c)).expand(h);return new f(r)};return t});
(function(f,h){"object"===typeof exports?module.exports=h(require("jquery","./URI")):"function"===typeof define&&define.amd?define(["jquery","./URI"],h):h(f.jQuery,f.URI)})(this,function(f, h){function t(c){return c.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")}function u(c){var k=c.nodeName.toLowerCase();return"input"===k&&"image"!==c.type?void 0:h.domAttributes[k]}function c(c){return{get:function(k){return f(k).uri()[c]()},set:function(k, h){f(k).uri()[c](h);return h}}}function y(c, k){var h,l,n;if(!u(c)||
!k)return!1;h=k.match(C);if(!h||!h[5]&&":"!==h[2]&&!r[h[2]])return!1;n=f(c).uri();if(h[5])return n.is(h[5]);if(":"===h[2])return l=h[1].toLowerCase()+":",r[l]?r[l](n,h[4]):!1;l=h[1].toLowerCase();return z[l]?r[h[2]](n[l](),h[4],l):!1}var z={},r={"=":function(c,k){return c===k},"^=":function(c,k){return!!(c+"").match(new RegExp("^"+t(k),"i"))},"$=":function(c,k){return!!(c+"").match(new RegExp(t(k)+"$","i"))},"*=":function(c,k,f){"directory"===f&&(c+="/");return!!(c+"").match(new RegExp(t(k),"i"))},
"equals:":function(c,f){return c.equals(f)},"is:":function(c,f){return c.is(f)}};f.each("origin authority directory domain filename fragment hash host hostname href password path pathname port protocol query resource scheme search subdomain suffix tld username".split(" "),function(g,h){z[h]=!0;f.attrHooks["uri:"+h]=c(h)});var p=function(c,h){return f(c).uri().href(h).toString()};f.each(["src","href","action","uri","cite"],function(c,h){f.attrHooks[h]={set:p}});f.attrHooks.uri.get=function(c){return f(c).uri()};
f.fn.uri=function(c){var f=this.first(),q=f.get(0),l=u(q);if(!l)throw Error('Element "'+q.nodeName+'" does not have either property: href, src, action, cite');if(void 0!==c){var n=f.data("uri");if(n)return n.href(c);c instanceof h||(c=h(c||""))}else{if(c=f.data("uri"))return c;c=h(f.attr(l)||"")}c._dom_element=q;c._dom_attribute=l;c.normalize();f.data("uri",c);return c};h.prototype.build=function(c){if(this._dom_element)this._string=h.build(this._parts),this._deferred_build=!1,this._dom_element.setAttribute(this._dom_attribute,
this._string),this._dom_element[this._dom_attribute]=this._string;else if(!0===c)this._deferred_build=!0;else if(void 0===c||this._deferred_build)this._string=h.build(this._parts),this._deferred_build=!1;return this};var w,C=/^([a-zA-Z]+)\s*([\^\$*]?=|:)\s*(['"]?)(.+)\3|^\s*([a-zA-Z0-9]+)\s*$/;w=f.expr.createPseudo?f.expr.createPseudo(function(c){return function(f){return y(f,c)}}):function(c,f,h){return y(c,h[3])};f.expr[":"].uri=w;return f});
