<?php
/**
 * @file
 * livingstone_user_feature.features.uuid_user.inc
 */

/**
 * Implements hook_uuid_features_default_users().
 */
function livingstone_user_feature_uuid_features_default_users() {
  $users = array();

  $users[] = array(
  'name' => 'nbanks',
  'mail' => 'nigel.g.banks@gmail.com',
  'theme' => '',
  'signature' => '',
  'signature_format' => NULL,
  'created' => 1491933389,
  'status' => 1,
  'timezone' => 'UTC',
  'language' => '',
  'picture' => 0,
  'init' => 'nigel.g.banks@gmail.com',
  'data' => FALSE,
  'uuid' => '0ff19f94-945c-48e1-bab1-4969fb58aea1',
  'roles' => array(
    2 => 'authenticated user',
  ),
  'date' => '2017-04-11 17:56:29 +0000',
);
  $users[] = array(
  'name' => 'awisnicki',
  'mail' => 'awisnicki@yahoo.com',
  'theme' => '',
  'signature' => '',
  'signature_format' => 'filtered_html',
  'created' => 1391113888,
  'status' => 1,
  'timezone' => 'America/Chicago',
  'language' => '',
  'picture' => 0,
  'init' => 'awisnicki@yahoo.com',
  'data' => FALSE,
  'uuid' => '22a82bbc-8b0b-4c39-99e4-a242ac324e01',
  'roles' => array(
    2 => 'authenticated user',
  ),
  'date' => '2014-01-30 20:31:28 +0000',
);
  $users[] = array(
  'name' => 'jlivingstone',
  'mail' => 'j.livingstone@qub.ac.uk',
  'theme' => '',
  'signature' => '',
  'signature_format' => 'full_html',
  'created' => 1479675122,
  'status' => 1,
  'timezone' => 'America/Chicago',
  'language' => '',
  'picture' => 0,
  'init' => 'j.livingstone@qub.ac.uk',
  'data' => FALSE,
  'uuid' => '3df3f9e3-42c1-4d4a-916d-753fac884cda',
  'roles' => array(
    2 => 'authenticated user',
  ),
  'date' => '2016-11-20 20:52:02 +0000',
);
  $users[] = array(
  'name' => 'hball',
  'mail' => 'ball.heather.f@gmail.com',
  'theme' => '',
  'signature' => '',
  'signature_format' => 'full_html',
  'created' => 1458848462,
  'status' => 1,
  'timezone' => 'America/Chicago',
  'language' => '',
  'picture' => 0,
  'init' => 'ball.heather.f@gmail.com',
  'data' => FALSE,
  'uuid' => '8d1f87c2-997d-4c84-88c9-dce2671c3f21',
  'roles' => array(
    2 => 'authenticated user',
  ),
  'date' => '2016-03-24 19:41:02 +0000',
);
  $users[] = array(
  'name' => 'aliff.angela',
  'mail' => 'aliff.angela@gmail.com',
  'theme' => '',
  'signature' => '',
  'signature_format' => 'filtered_html',
  'created' => 1429918009,
  'status' => 1,
  'timezone' => 'America/New_York',
  'language' => '',
  'picture' => 0,
  'init' => 'aliff.angela@gmail.com',
  'data' => FALSE,
  'uuid' => 'a628edfc-56a8-4876-a76e-baa93db9ff98',
  'roles' => array(
    2 => 'authenticated user',
  ),
  'date' => '2015-04-24 23:26:49 +0000',
);
  $users[] = array(
  'name' => 'wardmegan',
  'mail' => 'ward.megan.elizabeth@gmail.com',
  'theme' => '',
  'signature' => '',
  'signature_format' => 'filtered_html',
  'created' => 1418411612,
  'status' => 1,
  'timezone' => 'America/Chicago',
  'language' => '',
  'picture' => 0,
  'init' => 'ward.megan.elizabeth@gmail.com',
  'data' => FALSE,
  'uuid' => 'b4e02cab-d1cc-4ac6-a023-770d7de23a51',
  'roles' => array(
    2 => 'authenticated user',
  ),
  'date' => '2014-12-12 19:13:32 +0000',
);
  $users[] = array(
  'name' => 'akkumari',
  'mail' => 'akkumari@crimson.ua.edu',
  'theme' => '',
  'signature' => '',
  'signature_format' => 'filtered_html',
  'created' => 1418411471,
  'status' => 1,
  'timezone' => 'America/Chicago',
  'language' => '',
  'picture' => 0,
  'init' => 'akkumari@crimson.ua.edu',
  'data' => FALSE,
  'uuid' => 'ee5cc42a-742c-4288-8d33-4b53e0cf2587',
  'roles' => array(
    2 => 'authenticated user',
  ),
  'date' => '2014-12-12 19:11:11 +0000',
);
  return $users;
}
